// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controller

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeControllerComponents 初始化所有控制器组件
func InitializeControllerComponents(configPath string) (*Controller, error) {
	config, err := ProvideConfig(configPath)
	if err != nil {
		return nil, err
	}
	keyManager, err := ProvideKeyManager(config)
	if err != nil {
		return nil, err
	}
	client, err := ProvideEtcdClient(config)
	if err != nil {
		return nil, err
	}
	nacosManager, err := ProvideNacosManager(config)
	if err != nil {
		return nil, err
	}
	configManager, err := ProvideConfigManager(keyManager, client, config, nacosManager)
	if err != nil {
		return nil, err
	}
	resourceManager, err := ProvideResourceManager(keyManager, config)
	if err != nil {
		return nil, err
	}
	mongoClient, err := ProvideDBClient(config)
	if err != nil {
		return nil, err
	}
	registryManager, err := ProvideRegistryManager(keyManager, configManager, mongoClient)
	if err != nil {
		return nil, err
	}
	minioManager, err := ProvideMinioManager(keyManager, configManager, registryManager)
	if err != nil {
		return nil, err
	}
	deploymentManager := ProvideDeployManager(configManager, registryManager, minioManager, mongoClient)
	agentManager, err := ProvideAgentManager(registryManager, resourceManager, configManager, keyManager, minioManager, mongoClient, nacosManager)
	if err != nil {
		return nil, err
	}
	jumperServerManager := ProvideJumperServerManager(registryManager, keyManager, config)
	grpcProxyManager := ProvideGrpcProxyManager(registryManager, agentManager, keyManager, config)
	redisManager, err := ProvideRedisManager(config)
	if err != nil {
		return nil, err
	}
	lokiForwarder := ProvideLokiForwarder(configManager, redisManager)
	prometheusForwarder := ProvidePrometheusForwarder(configManager, redisManager)
	pluginTemplateService, err := ProvidePluginTemplateService(mongoClient, config)
	if err != nil {
		return nil, err
	}
	telegrafConfigGenerator, err := ProvideTelegrafConfigGenerator(pluginTemplateService, config)
	if err != nil {
		return nil, err
	}
	telegrafManager, err := ProvideTelegrafManager(resourceManager, configManager, registryManager, keyManager, config, telegrafConfigGenerator)
	if err != nil {
		return nil, err
	}
	monitoringService, err := ProvideMonitoringService(mongoClient, config, telegrafConfigGenerator, pluginTemplateService, telegrafManager)
	if err != nil {
		return nil, err
	}
	controller, err := ProvideController(configManager, resourceManager, registryManager, keyManager, minioManager, deploymentManager, mongoClient, agentManager, jumperServerManager, grpcProxyManager, lokiForwarder, prometheusForwarder, telegrafManager, redisManager, monitoringService, pluginTemplateService)
	if err != nil {
		return nil, err
	}
	return controller, nil
}

// wire.go:

// ProviderSet 是一个 Wire 提供者集合，包含了所有控制器组件的提供者
var ProviderSet = wire.NewSet(
	ProvideKeyManager,
	ProvideAgentManager,
	ProvideMinioManager,
	ProvideResourceManager,
	ProvideConfigManager,
	ProvideRegistryManager,
	ProvideEtcdClient,
	ProvideConfig,
	ProvideController,
	ProvideDeployManager,
	ProvideDBClient,
	ProvideJumperServerManager,
	ProvideGrpcProxyManager,
	ProvideLokiForwarder,
	ProvidePrometheusForwarder,
	ProvidePluginTemplateService,
	ProvideTelegrafConfigGenerator,
	ProvideTelegrafManager,
	ProvideMonitoringService,
	ProvideNacosManager,
	ProvideRedisManager,
)
