// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: command.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecCommandSignalType int32

const (
	ExecCommandSignalType_CANCEL ExecCommandSignalType = 0
	ExecCommandSignalType_PAUSE  ExecCommandSignalType = 1
	ExecCommandSignalType_RESUME ExecCommandSignalType = 2
)

// Enum value maps for ExecCommandSignalType.
var (
	ExecCommandSignalType_name = map[int32]string{
		0: "CANCEL",
		1: "PAUSE",
		2: "RESUME",
	}
	ExecCommandSignalType_value = map[string]int32{
		"CANCEL": 0,
		"PAUSE":  1,
		"RESUME": 2,
	}
)

func (x ExecCommandSignalType) Enum() *ExecCommandSignalType {
	p := new(ExecCommandSignalType)
	*p = x
	return p
}

func (x ExecCommandSignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecCommandSignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_command_proto_enumTypes[0].Descriptor()
}

func (ExecCommandSignalType) Type() protoreflect.EnumType {
	return &file_command_proto_enumTypes[0]
}

func (x ExecCommandSignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecCommandSignalType.Descriptor instead.
func (ExecCommandSignalType) EnumDescriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

type ExecCommandReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Continuous    bool                   `protobuf:"varint,2,opt,name=continuous,proto3" json:"continuous,omitempty"` // 标识是否为持续运行的命令
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommandReq) Reset() {
	*x = ExecCommandReq{}
	mi := &file_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommandReq) ProtoMessage() {}

func (x *ExecCommandReq) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommandReq.ProtoReflect.Descriptor instead.
func (*ExecCommandReq) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

func (x *ExecCommandReq) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecCommandReq) GetContinuous() bool {
	if x != nil {
		return x.Continuous
	}
	return false
}

type ExecCommandResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Out           string                 `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	CommandId     string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // 用于标识持续运行的命令
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommandResp) Reset() {
	*x = ExecCommandResp{}
	mi := &file_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommandResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommandResp) ProtoMessage() {}

func (x *ExecCommandResp) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommandResp.ProtoReflect.Descriptor instead.
func (*ExecCommandResp) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{1}
}

func (x *ExecCommandResp) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

func (x *ExecCommandResp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *ExecCommandResp) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type ExecCommandSignalReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Signal        ExecCommandSignalType  `protobuf:"varint,2,opt,name=signal,proto3,enum=pb.ExecCommandSignalType" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommandSignalReq) Reset() {
	*x = ExecCommandSignalReq{}
	mi := &file_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommandSignalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommandSignalReq) ProtoMessage() {}

func (x *ExecCommandSignalReq) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommandSignalReq.ProtoReflect.Descriptor instead.
func (*ExecCommandSignalReq) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{2}
}

func (x *ExecCommandSignalReq) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ExecCommandSignalReq) GetSignal() ExecCommandSignalType {
	if x != nil {
		return x.Signal
	}
	return ExecCommandSignalType_CANCEL
}

type ExecCommandSignalResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommandSignalResp) Reset() {
	*x = ExecCommandSignalResp{}
	mi := &file_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommandSignalResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommandSignalResp) ProtoMessage() {}

func (x *ExecCommandSignalResp) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommandSignalResp.ProtoReflect.Descriptor instead.
func (*ExecCommandSignalResp) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{3}
}

func (x *ExecCommandSignalResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetCommandStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandStatusReq) Reset() {
	*x = GetCommandStatusReq{}
	mi := &file_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandStatusReq) ProtoMessage() {}

func (x *GetCommandStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandStatusReq.ProtoReflect.Descriptor instead.
func (*GetCommandStatusReq) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{4}
}

func (x *GetCommandStatusReq) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type GetCommandStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Duration      float64                `protobuf:"fixed64,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandStatusResp) Reset() {
	*x = GetCommandStatusResp{}
	mi := &file_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandStatusResp) ProtoMessage() {}

func (x *GetCommandStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandStatusResp.ProtoReflect.Descriptor instead.
func (*GetCommandStatusResp) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{5}
}

func (x *GetCommandStatusResp) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *GetCommandStatusResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetCommandStatusResp) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetCommandStatusResp) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_command_proto protoreflect.FileDescriptor

const file_command_proto_rawDesc = "" +
	"\n" +
	"\rcommand.proto\x12\x02pb\"J\n" +
	"\x0eExecCommandReq\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1e\n" +
	"\n" +
	"continuous\x18\x02 \x01(\bR\n" +
	"continuous\"T\n" +
	"\x0fExecCommandResp\x12\x10\n" +
	"\x03out\x18\x01 \x01(\tR\x03out\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\"h\n" +
	"\x14ExecCommandSignalReq\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x121\n" +
	"\x06signal\x18\x02 \x01(\x0e2\x19.pb.ExecCommandSignalTypeR\x06signal\"1\n" +
	"\x15ExecCommandSignalResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\x13GetCommandStatusReq\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"\x88\x01\n" +
	"\x14GetCommandStatusResp\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x01R\bduration*:\n" +
	"\x15ExecCommandSignalType\x12\n" +
	"\n" +
	"\x06CANCEL\x10\x00\x12\t\n" +
	"\x05PAUSE\x10\x01\x12\n" +
	"\n" +
	"\x06RESUME\x10\x022\xd4\x01\n" +
	"\aCommand\x128\n" +
	"\vExecCommand\x12\x12.pb.ExecCommandReq\x1a\x13.pb.ExecCommandResp0\x01\x12H\n" +
	"\x11ExecCommandSignal\x12\x18.pb.ExecCommandSignalReq\x1a\x19.pb.ExecCommandSignalResp\x12E\n" +
	"\x10GetCommandStatus\x12\x17.pb.GetCommandStatusReq\x1a\x18.pb.GetCommandStatusRespB\x1dZ\x1bgithub.com/influxdata/telegraf/controller/pbb\x06proto3"

var (
	file_command_proto_rawDescOnce sync.Once
	file_command_proto_rawDescData []byte
)

func file_command_proto_rawDescGZIP() []byte {
	file_command_proto_rawDescOnce.Do(func() {
		file_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)))
	})
	return file_command_proto_rawDescData
}

var file_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_command_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_command_proto_goTypes = []any{
	(ExecCommandSignalType)(0),    // 0: pb.ExecCommandSignalType
	(*ExecCommandReq)(nil),        // 1: pb.ExecCommandReq
	(*ExecCommandResp)(nil),       // 2: pb.ExecCommandResp
	(*ExecCommandSignalReq)(nil),  // 3: pb.ExecCommandSignalReq
	(*ExecCommandSignalResp)(nil), // 4: pb.ExecCommandSignalResp
	(*GetCommandStatusReq)(nil),   // 5: pb.GetCommandStatusReq
	(*GetCommandStatusResp)(nil),  // 6: pb.GetCommandStatusResp
}
var file_command_proto_depIdxs = []int32{
	0, // 0: pb.ExecCommandSignalReq.signal:type_name -> pb.ExecCommandSignalType
	1, // 1: pb.Command.ExecCommand:input_type -> pb.ExecCommandReq
	3, // 2: pb.Command.ExecCommandSignal:input_type -> pb.ExecCommandSignalReq
	5, // 3: pb.Command.GetCommandStatus:input_type -> pb.GetCommandStatusReq
	2, // 4: pb.Command.ExecCommand:output_type -> pb.ExecCommandResp
	4, // 5: pb.Command.ExecCommandSignal:output_type -> pb.ExecCommandSignalResp
	6, // 6: pb.Command.GetCommandStatus:output_type -> pb.GetCommandStatusResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_command_proto_init() }
func file_command_proto_init() {
	if File_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_command_proto_goTypes,
		DependencyIndexes: file_command_proto_depIdxs,
		EnumInfos:         file_command_proto_enumTypes,
		MessageInfos:      file_command_proto_msgTypes,
	}.Build()
	File_command_proto = out.File
	file_command_proto_goTypes = nil
	file_command_proto_depIdxs = nil
}
