// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: command.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Command_ExecCommand_FullMethodName       = "/pb.Command/ExecCommand"
	Command_ExecCommandSignal_FullMethodName = "/pb.Command/ExecCommandSignal"
	Command_GetCommandStatus_FullMethodName  = "/pb.Command/GetCommandStatus"
)

// CommandClient is the client API for Command service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandClient interface {
	ExecCommand(ctx context.Context, in *ExecCommandReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecCommandResp], error)
	ExecCommandSignal(ctx context.Context, in *ExecCommandSignalReq, opts ...grpc.CallOption) (*ExecCommandSignalResp, error)
	GetCommandStatus(ctx context.Context, in *GetCommandStatusReq, opts ...grpc.CallOption) (*GetCommandStatusResp, error)
}

type commandClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandClient(cc grpc.ClientConnInterface) CommandClient {
	return &commandClient{cc}
}

func (c *commandClient) ExecCommand(ctx context.Context, in *ExecCommandReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecCommandResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Command_ServiceDesc.Streams[0], Command_ExecCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecCommandReq, ExecCommandResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Command_ExecCommandClient = grpc.ServerStreamingClient[ExecCommandResp]

func (c *commandClient) ExecCommandSignal(ctx context.Context, in *ExecCommandSignalReq, opts ...grpc.CallOption) (*ExecCommandSignalResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecCommandSignalResp)
	err := c.cc.Invoke(ctx, Command_ExecCommandSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandClient) GetCommandStatus(ctx context.Context, in *GetCommandStatusReq, opts ...grpc.CallOption) (*GetCommandStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommandStatusResp)
	err := c.cc.Invoke(ctx, Command_GetCommandStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandServer is the server API for Command service.
// All implementations must embed UnimplementedCommandServer
// for forward compatibility.
type CommandServer interface {
	ExecCommand(*ExecCommandReq, grpc.ServerStreamingServer[ExecCommandResp]) error
	ExecCommandSignal(context.Context, *ExecCommandSignalReq) (*ExecCommandSignalResp, error)
	GetCommandStatus(context.Context, *GetCommandStatusReq) (*GetCommandStatusResp, error)
	mustEmbedUnimplementedCommandServer()
}

// UnimplementedCommandServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandServer struct{}

func (UnimplementedCommandServer) ExecCommand(*ExecCommandReq, grpc.ServerStreamingServer[ExecCommandResp]) error {
	return status.Errorf(codes.Unimplemented, "method ExecCommand not implemented")
}
func (UnimplementedCommandServer) ExecCommandSignal(context.Context, *ExecCommandSignalReq) (*ExecCommandSignalResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecCommandSignal not implemented")
}
func (UnimplementedCommandServer) GetCommandStatus(context.Context, *GetCommandStatusReq) (*GetCommandStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommandStatus not implemented")
}
func (UnimplementedCommandServer) mustEmbedUnimplementedCommandServer() {}
func (UnimplementedCommandServer) testEmbeddedByValue()                 {}

// UnsafeCommandServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandServer will
// result in compilation errors.
type UnsafeCommandServer interface {
	mustEmbedUnimplementedCommandServer()
}

func RegisterCommandServer(s grpc.ServiceRegistrar, srv CommandServer) {
	// If the following call pancis, it indicates UnimplementedCommandServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Command_ServiceDesc, srv)
}

func _Command_ExecCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecCommandReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommandServer).ExecCommand(m, &grpc.GenericServerStream[ExecCommandReq, ExecCommandResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Command_ExecCommandServer = grpc.ServerStreamingServer[ExecCommandResp]

func _Command_ExecCommandSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecCommandSignalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServer).ExecCommandSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Command_ExecCommandSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServer).ExecCommandSignal(ctx, req.(*ExecCommandSignalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Command_GetCommandStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommandStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServer).GetCommandStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Command_GetCommandStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServer).GetCommandStatus(ctx, req.(*GetCommandStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Command_ServiceDesc is the grpc.ServiceDesc for Command service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Command_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Command",
	HandlerType: (*CommandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecCommandSignal",
			Handler:    _Command_ExecCommandSignal_Handler,
		},
		{
			MethodName: "GetCommandStatus",
			Handler:    _Command_GetCommandStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecCommand",
			Handler:       _Command_ExecCommand_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "command.proto",
}
