// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: agent/pb/file.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	File_ListFiles_FullMethodName       = "/pb.File/ListFiles"
	File_GetFileInfo_FullMethodName     = "/pb.File/GetFileInfo"
	File_StartFileUpload_FullMethodName = "/pb.File/StartFileUpload"
	File_UploadFileChunk_FullMethodName = "/pb.File/UploadFileChunk"
	File_GetUploadStatus_FullMethodName = "/pb.File/GetUploadStatus"
	File_DownloadFile_FullMethodName    = "/pb.File/DownloadFile"
	File_DeleteFile_FullMethodName      = "/pb.File/DeleteFile"
	File_CreateDirectory_FullMethodName = "/pb.File/CreateDirectory"
)

// FileClient is the client API for File service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// File 服务定义
type FileClient interface {
	// ListFiles 列出文件
	ListFiles(ctx context.Context, in *ListFilesReq, opts ...grpc.CallOption) (*ListFilesResp, error)
	// GetFileInfo 获取文件信息
	GetFileInfo(ctx context.Context, in *GetFileInfoReq, opts ...grpc.CallOption) (*GetFileInfoResp, error)
	// StartFileUpload 开始文件上传
	StartFileUpload(ctx context.Context, in *StartFileUploadReq, opts ...grpc.CallOption) (*StartFileUploadResp, error)
	// UploadFileChunk 上传文件块
	UploadFileChunk(ctx context.Context, in *UploadFileChunkReq, opts ...grpc.CallOption) (*UploadFileChunkResp, error)
	// GetUploadStatus 获取上传状态
	GetUploadStatus(ctx context.Context, in *GetUploadStatusReq, opts ...grpc.CallOption) (*GetUploadStatusResp, error)
	// DownloadFile 下载文件（流式）
	DownloadFile(ctx context.Context, in *DownloadFileReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadFileResp], error)
	// DeleteFile 删除文件或目录
	DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...grpc.CallOption) (*DeleteFileResp, error)
	// CreateDirectory 创建目录
	CreateDirectory(ctx context.Context, in *CreateDirectoryReq, opts ...grpc.CallOption) (*CreateDirectoryResp, error)
}

type fileClient struct {
	cc grpc.ClientConnInterface
}

func NewFileClient(cc grpc.ClientConnInterface) FileClient {
	return &fileClient{cc}
}

func (c *fileClient) ListFiles(ctx context.Context, in *ListFilesReq, opts ...grpc.CallOption) (*ListFilesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResp)
	err := c.cc.Invoke(ctx, File_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) GetFileInfo(ctx context.Context, in *GetFileInfoReq, opts ...grpc.CallOption) (*GetFileInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileInfoResp)
	err := c.cc.Invoke(ctx, File_GetFileInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) StartFileUpload(ctx context.Context, in *StartFileUploadReq, opts ...grpc.CallOption) (*StartFileUploadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartFileUploadResp)
	err := c.cc.Invoke(ctx, File_StartFileUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) UploadFileChunk(ctx context.Context, in *UploadFileChunkReq, opts ...grpc.CallOption) (*UploadFileChunkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileChunkResp)
	err := c.cc.Invoke(ctx, File_UploadFileChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) GetUploadStatus(ctx context.Context, in *GetUploadStatusReq, opts ...grpc.CallOption) (*GetUploadStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUploadStatusResp)
	err := c.cc.Invoke(ctx, File_GetUploadStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) DownloadFile(ctx context.Context, in *DownloadFileReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadFileResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &File_ServiceDesc.Streams[0], File_DownloadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadFileReq, DownloadFileResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type File_DownloadFileClient = grpc.ServerStreamingClient[DownloadFileResp]

func (c *fileClient) DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...grpc.CallOption) (*DeleteFileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileResp)
	err := c.cc.Invoke(ctx, File_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) CreateDirectory(ctx context.Context, in *CreateDirectoryReq, opts ...grpc.CallOption) (*CreateDirectoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDirectoryResp)
	err := c.cc.Invoke(ctx, File_CreateDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServer is the server API for File service.
// All implementations must embed UnimplementedFileServer
// for forward compatibility.
//
// File 服务定义
type FileServer interface {
	// ListFiles 列出文件
	ListFiles(context.Context, *ListFilesReq) (*ListFilesResp, error)
	// GetFileInfo 获取文件信息
	GetFileInfo(context.Context, *GetFileInfoReq) (*GetFileInfoResp, error)
	// StartFileUpload 开始文件上传
	StartFileUpload(context.Context, *StartFileUploadReq) (*StartFileUploadResp, error)
	// UploadFileChunk 上传文件块
	UploadFileChunk(context.Context, *UploadFileChunkReq) (*UploadFileChunkResp, error)
	// GetUploadStatus 获取上传状态
	GetUploadStatus(context.Context, *GetUploadStatusReq) (*GetUploadStatusResp, error)
	// DownloadFile 下载文件（流式）
	DownloadFile(*DownloadFileReq, grpc.ServerStreamingServer[DownloadFileResp]) error
	// DeleteFile 删除文件或目录
	DeleteFile(context.Context, *DeleteFileReq) (*DeleteFileResp, error)
	// CreateDirectory 创建目录
	CreateDirectory(context.Context, *CreateDirectoryReq) (*CreateDirectoryResp, error)
	mustEmbedUnimplementedFileServer()
}

// UnimplementedFileServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServer struct{}

func (UnimplementedFileServer) ListFiles(context.Context, *ListFilesReq) (*ListFilesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedFileServer) GetFileInfo(context.Context, *GetFileInfoReq) (*GetFileInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileInfo not implemented")
}
func (UnimplementedFileServer) StartFileUpload(context.Context, *StartFileUploadReq) (*StartFileUploadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method StartFileUpload not implemented")
}
func (UnimplementedFileServer) UploadFileChunk(context.Context, *UploadFileChunkReq) (*UploadFileChunkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadFileChunk not implemented")
}
func (UnimplementedFileServer) GetUploadStatus(context.Context, *GetUploadStatusReq) (*GetUploadStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUploadStatus not implemented")
}
func (UnimplementedFileServer) DownloadFile(*DownloadFileReq, grpc.ServerStreamingServer[DownloadFileResp]) error {
	return status.Error(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedFileServer) DeleteFile(context.Context, *DeleteFileReq) (*DeleteFileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedFileServer) CreateDirectory(context.Context, *CreateDirectoryReq) (*CreateDirectoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDirectory not implemented")
}
func (UnimplementedFileServer) mustEmbedUnimplementedFileServer() {}
func (UnimplementedFileServer) testEmbeddedByValue()              {}

// UnsafeFileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServer will
// result in compilation errors.
type UnsafeFileServer interface {
	mustEmbedUnimplementedFileServer()
}

func RegisterFileServer(s grpc.ServiceRegistrar, srv FileServer) {
	// If the following call panics, it indicates UnimplementedFileServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&File_ServiceDesc, srv)
}

func _File_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).ListFiles(ctx, req.(*ListFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_GetFileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).GetFileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_GetFileInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).GetFileInfo(ctx, req.(*GetFileInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_StartFileUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartFileUploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).StartFileUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_StartFileUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).StartFileUpload(ctx, req.(*StartFileUploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_UploadFileChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileChunkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).UploadFileChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_UploadFileChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).UploadFileChunk(ctx, req.(*UploadFileChunkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_GetUploadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).GetUploadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_GetUploadStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).GetUploadStatus(ctx, req.(*GetUploadStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileServer).DownloadFile(m, &grpc.GenericServerStream[DownloadFileReq, DownloadFileResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type File_DownloadFileServer = grpc.ServerStreamingServer[DownloadFileResp]

func _File_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).DeleteFile(ctx, req.(*DeleteFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_CreateDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDirectoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).CreateDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_CreateDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).CreateDirectory(ctx, req.(*CreateDirectoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// File_ServiceDesc is the grpc.ServiceDesc for File service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var File_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.File",
	HandlerType: (*FileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFiles",
			Handler:    _File_ListFiles_Handler,
		},
		{
			MethodName: "GetFileInfo",
			Handler:    _File_GetFileInfo_Handler,
		},
		{
			MethodName: "StartFileUpload",
			Handler:    _File_StartFileUpload_Handler,
		},
		{
			MethodName: "UploadFileChunk",
			Handler:    _File_UploadFileChunk_Handler,
		},
		{
			MethodName: "GetUploadStatus",
			Handler:    _File_GetUploadStatus_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _File_DeleteFile_Handler,
		},
		{
			MethodName: "CreateDirectory",
			Handler:    _File_CreateDirectory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadFile",
			Handler:       _File_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent/pb/file.proto",
}
