// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent/pb/file.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileInfo 文件信息
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	Md5           string                 `protobuf:"bytes,6,opt,name=md5,proto3" json:"md5,omitempty"`
	Sha256        string                 `protobuf:"bytes,7,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_agent_pb_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *FileInfo) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

func (x *FileInfo) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *FileInfo) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// ListFilesReq 列出文件请求
type ListFilesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // 目录路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesReq) Reset() {
	*x = ListFilesReq{}
	mi := &file_agent_pb_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesReq) ProtoMessage() {}

func (x *ListFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesReq.ProtoReflect.Descriptor instead.
func (*ListFilesReq) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{1}
}

func (x *ListFilesReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// ListFilesResp 列出文件响应
type ListFilesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Files         []*FileInfo            `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResp) Reset() {
	*x = ListFilesResp{}
	mi := &file_agent_pb_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResp) ProtoMessage() {}

func (x *ListFilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResp.ProtoReflect.Descriptor instead.
func (*ListFilesResp) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{2}
}

func (x *ListFilesResp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListFilesResp) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

// GetFileInfoReq 获取文件信息请求
type GetFileInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoReq) Reset() {
	*x = GetFileInfoReq{}
	mi := &file_agent_pb_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoReq) ProtoMessage() {}

func (x *GetFileInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoReq.ProtoReflect.Descriptor instead.
func (*GetFileInfoReq) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileInfoReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// GetFileInfoResp 获取文件信息响应
type GetFileInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoResp) Reset() {
	*x = GetFileInfoResp{}
	mi := &file_agent_pb_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoResp) ProtoMessage() {}

func (x *GetFileInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoResp.ProtoReflect.Descriptor instead.
func (*GetFileInfoResp) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileInfoResp) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *GetFileInfoResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// StartFileUploadReq 开始文件上传请求
type StartFileUploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Md5           string                 `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5,omitempty"`
	Sha256        string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFileUploadReq) Reset() {
	*x = StartFileUploadReq{}
	mi := &file_agent_pb_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFileUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFileUploadReq) ProtoMessage() {}

func (x *StartFileUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFileUploadReq.ProtoReflect.Descriptor instead.
func (*StartFileUploadReq) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{5}
}

func (x *StartFileUploadReq) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *StartFileUploadReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *StartFileUploadReq) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *StartFileUploadReq) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// StartFileUploadResp 开始文件上传响应
type StartFileUploadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ChunkSize     int64                  `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFileUploadResp) Reset() {
	*x = StartFileUploadResp{}
	mi := &file_agent_pb_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFileUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFileUploadResp) ProtoMessage() {}

func (x *StartFileUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFileUploadResp.ProtoReflect.Descriptor instead.
func (*StartFileUploadResp) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{6}
}

func (x *StartFileUploadResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartFileUploadResp) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *StartFileUploadResp) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

// UploadFileChunkReq 上传文件块请求
type UploadFileChunkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChunkIndex    int64                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileChunkReq) Reset() {
	*x = UploadFileChunkReq{}
	mi := &file_agent_pb_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileChunkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileChunkReq) ProtoMessage() {}

func (x *UploadFileChunkReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileChunkReq.ProtoReflect.Descriptor instead.
func (*UploadFileChunkReq) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{7}
}

func (x *UploadFileChunkReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UploadFileChunkReq) GetChunkIndex() int64 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *UploadFileChunkReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UploadFileChunkResp 上传文件块响应
type UploadFileChunkResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChunkIndex    int64                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileChunkResp) Reset() {
	*x = UploadFileChunkResp{}
	mi := &file_agent_pb_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileChunkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileChunkResp) ProtoMessage() {}

func (x *UploadFileChunkResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileChunkResp.ProtoReflect.Descriptor instead.
func (*UploadFileChunkResp) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{8}
}

func (x *UploadFileChunkResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UploadFileChunkResp) GetChunkIndex() int64 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *UploadFileChunkResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetUploadStatusReq 获取上传状态请求
type GetUploadStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadStatusReq) Reset() {
	*x = GetUploadStatusReq{}
	mi := &file_agent_pb_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadStatusReq) ProtoMessage() {}

func (x *GetUploadStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadStatusReq.ProtoReflect.Descriptor instead.
func (*GetUploadStatusReq) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{9}
}

func (x *GetUploadStatusReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// GetUploadStatusResp 获取上传状态响应
type GetUploadStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // uploading, completed, failed
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	ReceivedSize  int64                  `protobuf:"varint,4,opt,name=received_size,json=receivedSize,proto3" json:"received_size,omitempty"`
	Progress      float64                `protobuf:"fixed64,5,opt,name=progress,proto3" json:"progress,omitempty"` // 0-100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadStatusResp) Reset() {
	*x = GetUploadStatusResp{}
	mi := &file_agent_pb_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadStatusResp) ProtoMessage() {}

func (x *GetUploadStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadStatusResp.ProtoReflect.Descriptor instead.
func (*GetUploadStatusResp) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{10}
}

func (x *GetUploadStatusResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetUploadStatusResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetUploadStatusResp) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *GetUploadStatusResp) GetReceivedSize() int64 {
	if x != nil {
		return x.ReceivedSize
	}
	return 0
}

func (x *GetUploadStatusResp) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

// DownloadFileReq 下载文件请求
type DownloadFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // 可选：起始偏移量
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"` // 可选：读取长度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileReq) Reset() {
	*x = DownloadFileReq{}
	mi := &file_agent_pb_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileReq) ProtoMessage() {}

func (x *DownloadFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileReq.ProtoReflect.Descriptor instead.
func (*DownloadFileReq) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadFileReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DownloadFileReq) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DownloadFileReq) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// DownloadFileResp 下载文件响应（流式）
type DownloadFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResp) Reset() {
	*x = DownloadFileResp{}
	mi := &file_agent_pb_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResp) ProtoMessage() {}

func (x *DownloadFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResp.ProtoReflect.Descriptor instead.
func (*DownloadFileResp) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{12}
}

func (x *DownloadFileResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadFileResp) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DownloadFileResp) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

// DeleteFileReq 删除文件请求
type DeleteFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"` // 如果是目录，是否递归删除
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileReq) Reset() {
	*x = DeleteFileReq{}
	mi := &file_agent_pb_file_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileReq) ProtoMessage() {}

func (x *DeleteFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileReq.ProtoReflect.Descriptor instead.
func (*DeleteFileReq) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteFileReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeleteFileReq) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

// DeleteFileResp 删除文件响应
type DeleteFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResp) Reset() {
	*x = DeleteFileResp{}
	mi := &file_agent_pb_file_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResp) ProtoMessage() {}

func (x *DeleteFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResp.ProtoReflect.Descriptor instead.
func (*DeleteFileResp) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteFileResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteFileResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CreateDirectoryReq 创建目录请求
type CreateDirectoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"` // 目录权限模式（八进制，如 0755）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectoryReq) Reset() {
	*x = CreateDirectoryReq{}
	mi := &file_agent_pb_file_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectoryReq) ProtoMessage() {}

func (x *CreateDirectoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectoryReq.ProtoReflect.Descriptor instead.
func (*CreateDirectoryReq) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{15}
}

func (x *CreateDirectoryReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateDirectoryReq) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// CreateDirectoryResp 创建目录响应
type CreateDirectoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectoryResp) Reset() {
	*x = CreateDirectoryResp{}
	mi := &file_agent_pb_file_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectoryResp) ProtoMessage() {}

func (x *CreateDirectoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_file_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectoryResp.ProtoReflect.Descriptor instead.
func (*CreateDirectoryResp) Descriptor() ([]byte, []int) {
	return file_agent_pb_file_proto_rawDescGZIP(), []int{16}
}

func (x *CreateDirectoryResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateDirectoryResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_pb_file_proto protoreflect.FileDescriptor

const file_agent_pb_file_proto_rawDesc = "" +
	"\n" +
	"\x13agent/pb/file.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x125\n" +
	"\bmod_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\x12\x10\n" +
	"\x03md5\x18\x06 \x01(\tR\x03md5\x12\x16\n" +
	"\x06sha256\x18\a \x01(\tR\x06sha256\"\"\n" +
	"\fListFilesReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"G\n" +
	"\rListFilesResp\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\"\n" +
	"\x05files\x18\x02 \x03(\v2\f.pb.FileInfoR\x05files\"$\n" +
	"\x0eGetFileInfoReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"K\n" +
	"\x0fGetFileInfoResp\x12 \n" +
	"\x04file\x18\x01 \x01(\v2\f.pb.FileInfoR\x04file\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"x\n" +
	"\x12StartFileUploadReq\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\x12\x10\n" +
	"\x03md5\x18\x03 \x01(\tR\x03md5\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\"p\n" +
	"\x13StartFileUploadResp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\x03R\tchunkSize\"h\n" +
	"\x12UploadFileChunkReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x03R\n" +
	"chunkIndex\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"m\n" +
	"\x13UploadFileChunkResp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x03R\n" +
	"chunkIndex\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"3\n" +
	"\x12GetUploadStatusReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xac\x01\n" +
	"\x13GetUploadStatusResp\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12#\n" +
	"\rreceived_size\x18\x04 \x01(\x03R\freceivedSize\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x01R\bprogress\"U\n" +
	"\x0fDownloadFileReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\"P\n" +
	"\x10DownloadFileResp\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\"A\n" +
	"\rDeleteFileReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"D\n" +
	"\x0eDeleteFileResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"<\n" +
	"\x12CreateDirectoryReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\"I\n" +
	"\x13CreateDirectoryResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf2\x03\n" +
	"\x04File\x120\n" +
	"\tListFiles\x12\x10.pb.ListFilesReq\x1a\x11.pb.ListFilesResp\x126\n" +
	"\vGetFileInfo\x12\x12.pb.GetFileInfoReq\x1a\x13.pb.GetFileInfoResp\x12B\n" +
	"\x0fStartFileUpload\x12\x16.pb.StartFileUploadReq\x1a\x17.pb.StartFileUploadResp\x12B\n" +
	"\x0fUploadFileChunk\x12\x16.pb.UploadFileChunkReq\x1a\x17.pb.UploadFileChunkResp\x12B\n" +
	"\x0fGetUploadStatus\x12\x16.pb.GetUploadStatusReq\x1a\x17.pb.GetUploadStatusResp\x12;\n" +
	"\fDownloadFile\x12\x13.pb.DownloadFileReq\x1a\x14.pb.DownloadFileResp0\x01\x123\n" +
	"\n" +
	"DeleteFile\x12\x11.pb.DeleteFileReq\x1a\x12.pb.DeleteFileResp\x12B\n" +
	"\x0fCreateDirectory\x12\x16.pb.CreateDirectoryReq\x1a\x17.pb.CreateDirectoryRespB\x1dZ\x1bgithub.com/influxdata/telegraf/controller/pbb\x06proto3"

var (
	file_agent_pb_file_proto_rawDescOnce sync.Once
	file_agent_pb_file_proto_rawDescData []byte
)

func file_agent_pb_file_proto_rawDescGZIP() []byte {
	file_agent_pb_file_proto_rawDescOnce.Do(func() {
		file_agent_pb_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_pb_file_proto_rawDesc), len(file_agent_pb_file_proto_rawDesc)))
	})
	return file_agent_pb_file_proto_rawDescData
}

var file_agent_pb_file_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_agent_pb_file_proto_goTypes = []any{
	(*FileInfo)(nil),              // 0: pb.FileInfo
	(*ListFilesReq)(nil),          // 1: pb.ListFilesReq
	(*ListFilesResp)(nil),         // 2: pb.ListFilesResp
	(*GetFileInfoReq)(nil),        // 3: pb.GetFileInfoReq
	(*GetFileInfoResp)(nil),       // 4: pb.GetFileInfoResp
	(*StartFileUploadReq)(nil),    // 5: pb.StartFileUploadReq
	(*StartFileUploadResp)(nil),   // 6: pb.StartFileUploadResp
	(*UploadFileChunkReq)(nil),    // 7: pb.UploadFileChunkReq
	(*UploadFileChunkResp)(nil),   // 8: pb.UploadFileChunkResp
	(*GetUploadStatusReq)(nil),    // 9: pb.GetUploadStatusReq
	(*GetUploadStatusResp)(nil),   // 10: pb.GetUploadStatusResp
	(*DownloadFileReq)(nil),       // 11: pb.DownloadFileReq
	(*DownloadFileResp)(nil),      // 12: pb.DownloadFileResp
	(*DeleteFileReq)(nil),         // 13: pb.DeleteFileReq
	(*DeleteFileResp)(nil),        // 14: pb.DeleteFileResp
	(*CreateDirectoryReq)(nil),    // 15: pb.CreateDirectoryReq
	(*CreateDirectoryResp)(nil),   // 16: pb.CreateDirectoryResp
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_agent_pb_file_proto_depIdxs = []int32{
	17, // 0: pb.FileInfo.mod_time:type_name -> google.protobuf.Timestamp
	0,  // 1: pb.ListFilesResp.files:type_name -> pb.FileInfo
	0,  // 2: pb.GetFileInfoResp.file:type_name -> pb.FileInfo
	1,  // 3: pb.File.ListFiles:input_type -> pb.ListFilesReq
	3,  // 4: pb.File.GetFileInfo:input_type -> pb.GetFileInfoReq
	5,  // 5: pb.File.StartFileUpload:input_type -> pb.StartFileUploadReq
	7,  // 6: pb.File.UploadFileChunk:input_type -> pb.UploadFileChunkReq
	9,  // 7: pb.File.GetUploadStatus:input_type -> pb.GetUploadStatusReq
	11, // 8: pb.File.DownloadFile:input_type -> pb.DownloadFileReq
	13, // 9: pb.File.DeleteFile:input_type -> pb.DeleteFileReq
	15, // 10: pb.File.CreateDirectory:input_type -> pb.CreateDirectoryReq
	2,  // 11: pb.File.ListFiles:output_type -> pb.ListFilesResp
	4,  // 12: pb.File.GetFileInfo:output_type -> pb.GetFileInfoResp
	6,  // 13: pb.File.StartFileUpload:output_type -> pb.StartFileUploadResp
	8,  // 14: pb.File.UploadFileChunk:output_type -> pb.UploadFileChunkResp
	10, // 15: pb.File.GetUploadStatus:output_type -> pb.GetUploadStatusResp
	12, // 16: pb.File.DownloadFile:output_type -> pb.DownloadFileResp
	14, // 17: pb.File.DeleteFile:output_type -> pb.DeleteFileResp
	16, // 18: pb.File.CreateDirectory:output_type -> pb.CreateDirectoryResp
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_agent_pb_file_proto_init() }
func file_agent_pb_file_proto_init() {
	if File_agent_pb_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_pb_file_proto_rawDesc), len(file_agent_pb_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_pb_file_proto_goTypes,
		DependencyIndexes: file_agent_pb_file_proto_depIdxs,
		MessageInfos:      file_agent_pb_file_proto_msgTypes,
	}.Build()
	File_agent_pb_file_proto = out.File
	file_agent_pb_file_proto_goTypes = nil
	file_agent_pb_file_proto_depIdxs = nil
}
