// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: health.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Health_GetHealthStatus_FullMethodName    = "/pb.Health/GetHealthStatus"
	Health_ListHealthStatuses_FullMethodName = "/pb.Health/ListHealthStatuses"
	Health_GetHealthHistory_FullMethodName   = "/pb.Health/GetHealthHistory"
)

// HealthClient is the client API for Health service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Health 服务定义
type HealthClient interface {
	// GetHealthStatus 获取指定服务的健康状态
	GetHealthStatus(ctx context.Context, in *GetHealthStatusReq, opts ...grpc.CallOption) (*GetHealthStatusResp, error)
	// ListHealthStatuses 列出所有服务的健康状态
	ListHealthStatuses(ctx context.Context, in *ListHealthStatusesReq, opts ...grpc.CallOption) (*ListHealthStatusesResp, error)
	// GetHealthHistory 获取服务的健康检查历史
	GetHealthHistory(ctx context.Context, in *GetHealthHistoryReq, opts ...grpc.CallOption) (*GetHealthHistoryResp, error)
}

type healthClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthClient(cc grpc.ClientConnInterface) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) GetHealthStatus(ctx context.Context, in *GetHealthStatusReq, opts ...grpc.CallOption) (*GetHealthStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthStatusResp)
	err := c.cc.Invoke(ctx, Health_GetHealthStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) ListHealthStatuses(ctx context.Context, in *ListHealthStatusesReq, opts ...grpc.CallOption) (*ListHealthStatusesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHealthStatusesResp)
	err := c.cc.Invoke(ctx, Health_ListHealthStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) GetHealthHistory(ctx context.Context, in *GetHealthHistoryReq, opts ...grpc.CallOption) (*GetHealthHistoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthHistoryResp)
	err := c.cc.Invoke(ctx, Health_GetHealthHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServer is the server API for Health service.
// All implementations must embed UnimplementedHealthServer
// for forward compatibility.
//
// Health 服务定义
type HealthServer interface {
	// GetHealthStatus 获取指定服务的健康状态
	GetHealthStatus(context.Context, *GetHealthStatusReq) (*GetHealthStatusResp, error)
	// ListHealthStatuses 列出所有服务的健康状态
	ListHealthStatuses(context.Context, *ListHealthStatusesReq) (*ListHealthStatusesResp, error)
	// GetHealthHistory 获取服务的健康检查历史
	GetHealthHistory(context.Context, *GetHealthHistoryReq) (*GetHealthHistoryResp, error)
	mustEmbedUnimplementedHealthServer()
}

// UnimplementedHealthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServer struct{}

func (UnimplementedHealthServer) GetHealthStatus(context.Context, *GetHealthStatusReq) (*GetHealthStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealthStatus not implemented")
}
func (UnimplementedHealthServer) ListHealthStatuses(context.Context, *ListHealthStatusesReq) (*ListHealthStatusesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHealthStatuses not implemented")
}
func (UnimplementedHealthServer) GetHealthHistory(context.Context, *GetHealthHistoryReq) (*GetHealthHistoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealthHistory not implemented")
}
func (UnimplementedHealthServer) mustEmbedUnimplementedHealthServer() {}
func (UnimplementedHealthServer) testEmbeddedByValue()                {}

// UnsafeHealthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServer will
// result in compilation errors.
type UnsafeHealthServer interface {
	mustEmbedUnimplementedHealthServer()
}

func RegisterHealthServer(s grpc.ServiceRegistrar, srv HealthServer) {
	// If the following call pancis, it indicates UnimplementedHealthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Health_ServiceDesc, srv)
}

func _Health_GetHealthStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).GetHealthStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Health_GetHealthStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).GetHealthStatus(ctx, req.(*GetHealthStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_ListHealthStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHealthStatusesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).ListHealthStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Health_ListHealthStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).ListHealthStatuses(ctx, req.(*ListHealthStatusesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_GetHealthHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).GetHealthHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Health_GetHealthHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).GetHealthHistory(ctx, req.(*GetHealthHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Health_ServiceDesc is the grpc.ServiceDesc for Health service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Health_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealthStatus",
			Handler:    _Health_GetHealthStatus_Handler,
		},
		{
			MethodName: "ListHealthStatuses",
			Handler:    _Health_ListHealthStatuses_Handler,
		},
		{
			MethodName: "GetHealthHistory",
			Handler:    _Health_GetHealthHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health.proto",
}
