// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: health.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthStatus 健康状态枚举
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNKNOWN   HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY   HealthStatus = 1
	HealthStatus_HEALTH_STATUS_UNHEALTHY HealthStatus = 2
	HealthStatus_HEALTH_STATUS_DEGRADED  HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNKNOWN",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_UNHEALTHY",
		3: "HEALTH_STATUS_DEGRADED",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNKNOWN":   0,
		"HEALTH_STATUS_HEALTHY":   1,
		"HEALTH_STATUS_UNHEALTHY": 2,
		"HEALTH_STATUS_DEGRADED":  3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_health_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_health_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

// HealthStatusDetail 健康状态详情
type HealthStatusDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=pb.HealthStatus" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LastCheck      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	CheckType      string                 `protobuf:"bytes,4,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"`
	ResponseTimeMs int64                  `protobuf:"varint,5,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	Error          string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthStatusDetail) Reset() {
	*x = HealthStatusDetail{}
	mi := &file_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatusDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatusDetail) ProtoMessage() {}

func (x *HealthStatusDetail) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatusDetail.ProtoReflect.Descriptor instead.
func (*HealthStatusDetail) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthStatusDetail) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNKNOWN
}

func (x *HealthStatusDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthStatusDetail) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

func (x *HealthStatusDetail) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *HealthStatusDetail) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *HealthStatusDetail) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ServiceHealth 服务健康状态
type ServiceHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Status        HealthStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=pb.HealthStatus" json:"status,omitempty"`
	LastCheck     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Details       []*HealthStatusDetail  `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHealth) Reset() {
	*x = ServiceHealth{}
	mi := &file_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHealth) ProtoMessage() {}

func (x *ServiceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHealth.ProtoReflect.Descriptor instead.
func (*ServiceHealth) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceHealth) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *ServiceHealth) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNKNOWN
}

func (x *ServiceHealth) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

func (x *ServiceHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServiceHealth) GetDetails() []*HealthStatusDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

// GetHealthStatusReq 获取健康状态请求
type GetHealthStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthStatusReq) Reset() {
	*x = GetHealthStatusReq{}
	mi := &file_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthStatusReq) ProtoMessage() {}

func (x *GetHealthStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthStatusReq.ProtoReflect.Descriptor instead.
func (*GetHealthStatusReq) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{2}
}

func (x *GetHealthStatusReq) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

// GetHealthStatusResp 获取健康状态响应
type GetHealthStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *ServiceHealth         `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthStatusResp) Reset() {
	*x = GetHealthStatusResp{}
	mi := &file_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthStatusResp) ProtoMessage() {}

func (x *GetHealthStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthStatusResp.ProtoReflect.Descriptor instead.
func (*GetHealthStatusResp) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{3}
}

func (x *GetHealthStatusResp) GetHealth() *ServiceHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

// ListHealthStatusesReq 列出所有健康状态请求
type ListHealthStatusesReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 可选：只返回指定状态的服务
	FilterStatus  []HealthStatus `protobuf:"varint,1,rep,packed,name=filter_status,json=filterStatus,proto3,enum=pb.HealthStatus" json:"filter_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHealthStatusesReq) Reset() {
	*x = ListHealthStatusesReq{}
	mi := &file_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHealthStatusesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHealthStatusesReq) ProtoMessage() {}

func (x *ListHealthStatusesReq) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHealthStatusesReq.ProtoReflect.Descriptor instead.
func (*ListHealthStatusesReq) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{4}
}

func (x *ListHealthStatusesReq) GetFilterStatus() []HealthStatus {
	if x != nil {
		return x.FilterStatus
	}
	return nil
}

// ListHealthStatusesResp 列出所有健康状态响应
type ListHealthStatusesResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HealthStatuses []*ServiceHealth       `protobuf:"bytes,1,rep,name=health_statuses,json=healthStatuses,proto3" json:"health_statuses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListHealthStatusesResp) Reset() {
	*x = ListHealthStatusesResp{}
	mi := &file_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHealthStatusesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHealthStatusesResp) ProtoMessage() {}

func (x *ListHealthStatusesResp) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHealthStatusesResp.ProtoReflect.Descriptor instead.
func (*ListHealthStatusesResp) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{5}
}

func (x *ListHealthStatusesResp) GetHealthStatuses() []*ServiceHealth {
	if x != nil {
		return x.HealthStatuses
	}
	return nil
}

// GetHealthHistoryReq 获取健康检查历史请求
type GetHealthHistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 返回的记录数限制，默认 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthHistoryReq) Reset() {
	*x = GetHealthHistoryReq{}
	mi := &file_health_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthHistoryReq) ProtoMessage() {}

func (x *GetHealthHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthHistoryReq.ProtoReflect.Descriptor instead.
func (*GetHealthHistoryReq) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{6}
}

func (x *GetHealthHistoryReq) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *GetHealthHistoryReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// HealthHistoryEntry 健康检查历史记录
type HealthHistoryEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=pb.HealthStatus" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CheckType      string                 `protobuf:"bytes,4,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"`
	ResponseTimeMs int64                  `protobuf:"varint,5,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	Error          string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthHistoryEntry) Reset() {
	*x = HealthHistoryEntry{}
	mi := &file_health_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthHistoryEntry) ProtoMessage() {}

func (x *HealthHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthHistoryEntry.ProtoReflect.Descriptor instead.
func (*HealthHistoryEntry) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{7}
}

func (x *HealthHistoryEntry) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNKNOWN
}

func (x *HealthHistoryEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthHistoryEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthHistoryEntry) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *HealthHistoryEntry) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *HealthHistoryEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetHealthHistoryResp 获取健康检查历史响应
type GetHealthHistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Entries       []*HealthHistoryEntry  `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthHistoryResp) Reset() {
	*x = GetHealthHistoryResp{}
	mi := &file_health_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthHistoryResp) ProtoMessage() {}

func (x *GetHealthHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthHistoryResp.ProtoReflect.Descriptor instead.
func (*GetHealthHistoryResp) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{8}
}

func (x *GetHealthHistoryResp) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *GetHealthHistoryResp) GetEntries() []*HealthHistoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_health_proto protoreflect.FileDescriptor

const file_health_proto_rawDesc = "" +
	"\n" +
	"\fhealth.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x01\n" +
	"\x12HealthStatusDetail\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x10.pb.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\n" +
	"last_check\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\x12\x1d\n" +
	"\n" +
	"check_type\x18\x04 \x01(\tR\tcheckType\x12(\n" +
	"\x10response_time_ms\x18\x05 \x01(\x03R\x0eresponseTimeMs\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xda\x01\n" +
	"\rServiceHealth\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.pb.HealthStatusR\x06status\x129\n" +
	"\n" +
	"last_check\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x120\n" +
	"\adetails\x18\x05 \x03(\v2\x16.pb.HealthStatusDetailR\adetails\".\n" +
	"\x12GetHealthStatusReq\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\"@\n" +
	"\x13GetHealthStatusResp\x12)\n" +
	"\x06health\x18\x01 \x01(\v2\x11.pb.ServiceHealthR\x06health\"N\n" +
	"\x15ListHealthStatusesReq\x125\n" +
	"\rfilter_status\x18\x01 \x03(\x0e2\x10.pb.HealthStatusR\ffilterStatus\"T\n" +
	"\x16ListHealthStatusesResp\x12:\n" +
	"\x0fhealth_statuses\x18\x01 \x03(\v2\x11.pb.ServiceHealthR\x0ehealthStatuses\"E\n" +
	"\x13GetHealthHistoryReq\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xf1\x01\n" +
	"\x12HealthHistoryEntry\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x10.pb.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"check_type\x18\x04 \x01(\tR\tcheckType\x12(\n" +
	"\x10response_time_ms\x18\x05 \x01(\x03R\x0eresponseTimeMs\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"b\n" +
	"\x14GetHealthHistoryResp\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x120\n" +
	"\aentries\x18\x02 \x03(\v2\x16.pb.HealthHistoryEntryR\aentries*}\n" +
	"\fHealthStatus\x12\x19\n" +
	"\x15HEALTH_STATUS_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x02\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x032\xe0\x01\n" +
	"\x06Health\x12B\n" +
	"\x0fGetHealthStatus\x12\x16.pb.GetHealthStatusReq\x1a\x17.pb.GetHealthStatusResp\x12K\n" +
	"\x12ListHealthStatuses\x12\x19.pb.ListHealthStatusesReq\x1a\x1a.pb.ListHealthStatusesResp\x12E\n" +
	"\x10GetHealthHistory\x12\x17.pb.GetHealthHistoryReq\x1a\x18.pb.GetHealthHistoryRespB\x1dZ\x1bgithub.com/influxdata/telegraf/controller/pbb\x06proto3"

var (
	file_health_proto_rawDescOnce sync.Once
	file_health_proto_rawDescData []byte
)

func file_health_proto_rawDescGZIP() []byte {
	file_health_proto_rawDescOnce.Do(func() {
		file_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)))
	})
	return file_health_proto_rawDescData
}

var file_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_health_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_health_proto_goTypes = []any{
	(HealthStatus)(0),              // 0: pb.HealthStatus
	(*HealthStatusDetail)(nil),     // 1: pb.HealthStatusDetail
	(*ServiceHealth)(nil),          // 2: pb.ServiceHealth
	(*GetHealthStatusReq)(nil),     // 3: pb.GetHealthStatusReq
	(*GetHealthStatusResp)(nil),    // 4: pb.GetHealthStatusResp
	(*ListHealthStatusesReq)(nil),  // 5: pb.ListHealthStatusesReq
	(*ListHealthStatusesResp)(nil), // 6: pb.ListHealthStatusesResp
	(*GetHealthHistoryReq)(nil),    // 7: pb.GetHealthHistoryReq
	(*HealthHistoryEntry)(nil),     // 8: pb.HealthHistoryEntry
	(*GetHealthHistoryResp)(nil),   // 9: pb.GetHealthHistoryResp
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
}
var file_health_proto_depIdxs = []int32{
	0,  // 0: pb.HealthStatusDetail.status:type_name -> pb.HealthStatus
	10, // 1: pb.HealthStatusDetail.last_check:type_name -> google.protobuf.Timestamp
	0,  // 2: pb.ServiceHealth.status:type_name -> pb.HealthStatus
	10, // 3: pb.ServiceHealth.last_check:type_name -> google.protobuf.Timestamp
	1,  // 4: pb.ServiceHealth.details:type_name -> pb.HealthStatusDetail
	2,  // 5: pb.GetHealthStatusResp.health:type_name -> pb.ServiceHealth
	0,  // 6: pb.ListHealthStatusesReq.filter_status:type_name -> pb.HealthStatus
	2,  // 7: pb.ListHealthStatusesResp.health_statuses:type_name -> pb.ServiceHealth
	0,  // 8: pb.HealthHistoryEntry.status:type_name -> pb.HealthStatus
	10, // 9: pb.HealthHistoryEntry.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 10: pb.GetHealthHistoryResp.entries:type_name -> pb.HealthHistoryEntry
	3,  // 11: pb.Health.GetHealthStatus:input_type -> pb.GetHealthStatusReq
	5,  // 12: pb.Health.ListHealthStatuses:input_type -> pb.ListHealthStatusesReq
	7,  // 13: pb.Health.GetHealthHistory:input_type -> pb.GetHealthHistoryReq
	4,  // 14: pb.Health.GetHealthStatus:output_type -> pb.GetHealthStatusResp
	6,  // 15: pb.Health.ListHealthStatuses:output_type -> pb.ListHealthStatusesResp
	9,  // 16: pb.Health.GetHealthHistory:output_type -> pb.GetHealthHistoryResp
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_health_proto_init() }
func file_health_proto_init() {
	if File_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_proto_goTypes,
		DependencyIndexes: file_health_proto_depIdxs,
		EnumInfos:         file_health_proto_enumTypes,
		MessageInfos:      file_health_proto_msgTypes,
	}.Build()
	File_health_proto = out.File
	file_health_proto_goTypes = nil
	file_health_proto_depIdxs = nil
}
