// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: lua.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecLuaScriptResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentCode     string                 `protobuf:"bytes,1,opt,name=agentCode,proto3" json:"agentCode,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecLuaScriptResp) Reset() {
	*x = ExecLuaScriptResp{}
	mi := &file_lua_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecLuaScriptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecLuaScriptResp) ProtoMessage() {}

func (x *ExecLuaScriptResp) ProtoReflect() protoreflect.Message {
	mi := &file_lua_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecLuaScriptResp.ProtoReflect.Descriptor instead.
func (*ExecLuaScriptResp) Descriptor() ([]byte, []int) {
	return file_lua_proto_rawDescGZIP(), []int{0}
}

func (x *ExecLuaScriptResp) GetAgentCode() string {
	if x != nil {
		return x.AgentCode
	}
	return ""
}

func (x *ExecLuaScriptResp) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ExecLuaScriptReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentCode     string                 `protobuf:"bytes,1,opt,name=agentCode,proto3" json:"agentCode,omitempty"`
	Lua           string                 `protobuf:"bytes,2,opt,name=lua,proto3" json:"lua,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecLuaScriptReq) Reset() {
	*x = ExecLuaScriptReq{}
	mi := &file_lua_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecLuaScriptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecLuaScriptReq) ProtoMessage() {}

func (x *ExecLuaScriptReq) ProtoReflect() protoreflect.Message {
	mi := &file_lua_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecLuaScriptReq.ProtoReflect.Descriptor instead.
func (*ExecLuaScriptReq) Descriptor() ([]byte, []int) {
	return file_lua_proto_rawDescGZIP(), []int{1}
}

func (x *ExecLuaScriptReq) GetAgentCode() string {
	if x != nil {
		return x.AgentCode
	}
	return ""
}

func (x *ExecLuaScriptReq) GetLua() string {
	if x != nil {
		return x.Lua
	}
	return ""
}

var File_lua_proto protoreflect.FileDescriptor

const file_lua_proto_rawDesc = "" +
	"\n" +
	"\tlua.proto\x12\x02pb\"I\n" +
	"\x11ExecLuaScriptResp\x12\x1c\n" +
	"\tagentCode\x18\x01 \x01(\tR\tagentCode\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\"B\n" +
	"\x10ExecLuaScriptReq\x12\x1c\n" +
	"\tagentCode\x18\x01 \x01(\tR\tagentCode\x12\x10\n" +
	"\x03lua\x18\x02 \x01(\tR\x03lua2C\n" +
	"\x03Lua\x12<\n" +
	"\rExecLuaScript\x12\x14.pb.ExecLuaScriptReq\x1a\x15.pb.ExecLuaScriptRespB\x1dZ\x1bgithub.com/influxdata/telegraf/controller/pbb\x06proto3"

var (
	file_lua_proto_rawDescOnce sync.Once
	file_lua_proto_rawDescData []byte
)

func file_lua_proto_rawDescGZIP() []byte {
	file_lua_proto_rawDescOnce.Do(func() {
		file_lua_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lua_proto_rawDesc), len(file_lua_proto_rawDesc)))
	})
	return file_lua_proto_rawDescData
}

var file_lua_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lua_proto_goTypes = []any{
	(*ExecLuaScriptResp)(nil), // 0: pb.ExecLuaScriptResp
	(*ExecLuaScriptReq)(nil),  // 1: pb.ExecLuaScriptReq
}
var file_lua_proto_depIdxs = []int32{
	1, // 0: pb.Lua.ExecLuaScript:input_type -> pb.ExecLuaScriptReq
	0, // 1: pb.Lua.ExecLuaScript:output_type -> pb.ExecLuaScriptResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lua_proto_init() }
func file_lua_proto_init() {
	if File_lua_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lua_proto_rawDesc), len(file_lua_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lua_proto_goTypes,
		DependencyIndexes: file_lua_proto_depIdxs,
		MessageInfos:      file_lua_proto_msgTypes,
	}.Build()
	File_lua_proto = out.File
	file_lua_proto_goTypes = nil
	file_lua_proto_depIdxs = nil
}
