// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: lua.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Lua_ExecLuaScript_FullMethodName = "/pb.Lua/ExecLuaScript"
)

// LuaClient is the client API for Lua service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LuaClient interface {
	ExecLuaScript(ctx context.Context, in *ExecLuaScriptReq, opts ...grpc.CallOption) (*ExecLuaScriptResp, error)
}

type luaClient struct {
	cc grpc.ClientConnInterface
}

func NewLuaClient(cc grpc.ClientConnInterface) LuaClient {
	return &luaClient{cc}
}

func (c *luaClient) ExecLuaScript(ctx context.Context, in *ExecLuaScriptReq, opts ...grpc.CallOption) (*ExecLuaScriptResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecLuaScriptResp)
	err := c.cc.Invoke(ctx, Lua_ExecLuaScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LuaServer is the server API for Lua service.
// All implementations must embed UnimplementedLuaServer
// for forward compatibility.
type LuaServer interface {
	ExecLuaScript(context.Context, *ExecLuaScriptReq) (*ExecLuaScriptResp, error)
	mustEmbedUnimplementedLuaServer()
}

// UnimplementedLuaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLuaServer struct{}

func (UnimplementedLuaServer) ExecLuaScript(context.Context, *ExecLuaScriptReq) (*ExecLuaScriptResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecLuaScript not implemented")
}
func (UnimplementedLuaServer) mustEmbedUnimplementedLuaServer() {}
func (UnimplementedLuaServer) testEmbeddedByValue()             {}

// UnsafeLuaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LuaServer will
// result in compilation errors.
type UnsafeLuaServer interface {
	mustEmbedUnimplementedLuaServer()
}

func RegisterLuaServer(s grpc.ServiceRegistrar, srv LuaServer) {
	// If the following call pancis, it indicates UnimplementedLuaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Lua_ServiceDesc, srv)
}

func _Lua_ExecLuaScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecLuaScriptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuaServer).ExecLuaScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lua_ExecLuaScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuaServer).ExecLuaScript(ctx, req.(*ExecLuaScriptReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Lua_ServiceDesc is the grpc.ServiceDesc for Lua service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lua_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Lua",
	HandlerType: (*LuaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecLuaScript",
			Handler:    _Lua_ExecLuaScript_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lua.proto",
}
