// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent/pb/metrics.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceMetrics 服务指标
type ServiceMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Package        string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	CpuUsage       float64                `protobuf:"fixed64,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`                     // CPU 使用率（百分比）
	MemoryUsage    float64                `protobuf:"fixed64,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`            // 内存使用率（百分比）
	MemoryBytes    int64                  `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`             // 内存使用量（字节）
	DiskUsage      float64                `protobuf:"fixed64,5,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`                  // 磁盘使用率（百分比）
	NetworkIn      int64                  `protobuf:"varint,6,opt,name=network_in,json=networkIn,proto3" json:"network_in,omitempty"`                   // 网络入流量（字节）
	NetworkOut     int64                  `protobuf:"varint,7,opt,name=network_out,json=networkOut,proto3" json:"network_out,omitempty"`                // 网络出流量（字节）
	RequestCount   int64                  `protobuf:"varint,8,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`          // 请求数
	ErrorCount     int64                  `protobuf:"varint,9,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`                // 错误数
	ResponseTimeMs int64                  `protobuf:"varint,10,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"` // 响应时间（毫秒）
	LastUpdated    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServiceMetrics) Reset() {
	*x = ServiceMetrics{}
	mi := &file_agent_pb_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMetrics) ProtoMessage() {}

func (x *ServiceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMetrics.ProtoReflect.Descriptor instead.
func (*ServiceMetrics) Descriptor() ([]byte, []int) {
	return file_agent_pb_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceMetrics) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *ServiceMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ServiceMetrics) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ServiceMetrics) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ServiceMetrics) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *ServiceMetrics) GetNetworkIn() int64 {
	if x != nil {
		return x.NetworkIn
	}
	return 0
}

func (x *ServiceMetrics) GetNetworkOut() int64 {
	if x != nil {
		return x.NetworkOut
	}
	return 0
}

func (x *ServiceMetrics) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *ServiceMetrics) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *ServiceMetrics) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *ServiceMetrics) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// NetworkInterface 网络接口信息
type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                       // 接口名称
	RxBytes       int64                  `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"` // 接收字节数
	TxBytes       int64                  `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"` // 发送字节数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_agent_pb_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_agent_pb_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NetworkInterface) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

// SystemMetrics 系统指标
type SystemMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage          float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`                           // CPU 使用率（百分比）
	CpuCores          int32                  `protobuf:"varint,14,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`                           // CPU 核心数
	MemoryUsage       float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`                  // 内存使用率（百分比）
	MemoryTotal       int64                  `protobuf:"varint,3,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`                   // 总内存（字节）
	MemoryFree        int64                  `protobuf:"varint,4,opt,name=memory_free,json=memoryFree,proto3" json:"memory_free,omitempty"`                      // 空闲内存（字节）
	DiskUsage         float64                `protobuf:"fixed64,5,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`                        // 磁盘使用率（百分比）
	DiskTotal         int64                  `protobuf:"varint,6,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`                         // 总磁盘空间（字节）
	DiskFree          int64                  `protobuf:"varint,7,opt,name=disk_free,json=diskFree,proto3" json:"disk_free,omitempty"`                            // 空闲磁盘空间（字节）
	NetworkIn         int64                  `protobuf:"varint,8,opt,name=network_in,json=networkIn,proto3" json:"network_in,omitempty"`                         // 网络入流量（字节，已废弃，使用 network_interfaces）
	NetworkOut        int64                  `protobuf:"varint,9,opt,name=network_out,json=networkOut,proto3" json:"network_out,omitempty"`                      // 网络出流量（字节，已废弃，使用 network_interfaces）
	NetworkInterfaces []*NetworkInterface    `protobuf:"bytes,15,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"` // 网络接口列表
	LoadAvg_1         float64                `protobuf:"fixed64,10,opt,name=load_avg_1,json=loadAvg1,proto3" json:"load_avg_1,omitempty"`                        // 1分钟负载平均值
	LoadAvg_5         float64                `protobuf:"fixed64,11,opt,name=load_avg_5,json=loadAvg5,proto3" json:"load_avg_5,omitempty"`                        // 5分钟负载平均值
	LoadAvg_15        float64                `protobuf:"fixed64,12,opt,name=load_avg_15,json=loadAvg15,proto3" json:"load_avg_15,omitempty"`                     // 15分钟负载平均值
	LastUpdated       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_agent_pb_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_agent_pb_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *SystemMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemMetrics) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *SystemMetrics) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *SystemMetrics) GetMemoryFree() int64 {
	if x != nil {
		return x.MemoryFree
	}
	return 0
}

func (x *SystemMetrics) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *SystemMetrics) GetDiskTotal() int64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *SystemMetrics) GetDiskFree() int64 {
	if x != nil {
		return x.DiskFree
	}
	return 0
}

func (x *SystemMetrics) GetNetworkIn() int64 {
	if x != nil {
		return x.NetworkIn
	}
	return 0
}

func (x *SystemMetrics) GetNetworkOut() int64 {
	if x != nil {
		return x.NetworkOut
	}
	return 0
}

func (x *SystemMetrics) GetNetworkInterfaces() []*NetworkInterface {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

func (x *SystemMetrics) GetLoadAvg_1() float64 {
	if x != nil {
		return x.LoadAvg_1
	}
	return 0
}

func (x *SystemMetrics) GetLoadAvg_5() float64 {
	if x != nil {
		return x.LoadAvg_5
	}
	return 0
}

func (x *SystemMetrics) GetLoadAvg_15() float64 {
	if x != nil {
		return x.LoadAvg_15
	}
	return 0
}

func (x *SystemMetrics) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// GetSystemMetricsReq 获取系统指标请求
type GetSystemMetricsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemMetricsReq) Reset() {
	*x = GetSystemMetricsReq{}
	mi := &file_agent_pb_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemMetricsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemMetricsReq) ProtoMessage() {}

func (x *GetSystemMetricsReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemMetricsReq.ProtoReflect.Descriptor instead.
func (*GetSystemMetricsReq) Descriptor() ([]byte, []int) {
	return file_agent_pb_metrics_proto_rawDescGZIP(), []int{3}
}

// GetSystemMetricsResp 获取系统指标响应
type GetSystemMetricsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *SystemMetrics         `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemMetricsResp) Reset() {
	*x = GetSystemMetricsResp{}
	mi := &file_agent_pb_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemMetricsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemMetricsResp) ProtoMessage() {}

func (x *GetSystemMetricsResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemMetricsResp.ProtoReflect.Descriptor instead.
func (*GetSystemMetricsResp) Descriptor() ([]byte, []int) {
	return file_agent_pb_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *GetSystemMetricsResp) GetMetrics() *SystemMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// GetServiceMetricsReq 获取服务指标请求
type GetServiceMetricsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceMetricsReq) Reset() {
	*x = GetServiceMetricsReq{}
	mi := &file_agent_pb_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceMetricsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceMetricsReq) ProtoMessage() {}

func (x *GetServiceMetricsReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceMetricsReq.ProtoReflect.Descriptor instead.
func (*GetServiceMetricsReq) Descriptor() ([]byte, []int) {
	return file_agent_pb_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *GetServiceMetricsReq) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

// GetServiceMetricsResp 获取服务指标响应
type GetServiceMetricsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *ServiceMetrics        `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceMetricsResp) Reset() {
	*x = GetServiceMetricsResp{}
	mi := &file_agent_pb_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceMetricsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceMetricsResp) ProtoMessage() {}

func (x *GetServiceMetricsResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceMetricsResp.ProtoReflect.Descriptor instead.
func (*GetServiceMetricsResp) Descriptor() ([]byte, []int) {
	return file_agent_pb_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *GetServiceMetricsResp) GetMetrics() *ServiceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// ListServiceMetricsReq 列出所有服务指标请求
type ListServiceMetricsReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 可选：只返回运行中的服务
	RunningOnly   bool `protobuf:"varint,1,opt,name=running_only,json=runningOnly,proto3" json:"running_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceMetricsReq) Reset() {
	*x = ListServiceMetricsReq{}
	mi := &file_agent_pb_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceMetricsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceMetricsReq) ProtoMessage() {}

func (x *ListServiceMetricsReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceMetricsReq.ProtoReflect.Descriptor instead.
func (*ListServiceMetricsReq) Descriptor() ([]byte, []int) {
	return file_agent_pb_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *ListServiceMetricsReq) GetRunningOnly() bool {
	if x != nil {
		return x.RunningOnly
	}
	return false
}

// ListServiceMetricsResp 列出所有服务指标响应
type ListServiceMetricsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*ServiceMetrics      `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceMetricsResp) Reset() {
	*x = ListServiceMetricsResp{}
	mi := &file_agent_pb_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceMetricsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceMetricsResp) ProtoMessage() {}

func (x *ListServiceMetricsResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceMetricsResp.ProtoReflect.Descriptor instead.
func (*ListServiceMetricsResp) Descriptor() ([]byte, []int) {
	return file_agent_pb_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *ListServiceMetricsResp) GetMetrics() []*ServiceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// ApplicationMetrics 应用指标
type ApplicationMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // 指标名称 -> 指标值
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`     // 指标标签
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationMetrics) Reset() {
	*x = ApplicationMetrics{}
	mi := &file_agent_pb_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationMetrics) ProtoMessage() {}

func (x *ApplicationMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationMetrics.ProtoReflect.Descriptor instead.
func (*ApplicationMetrics) Descriptor() ([]byte, []int) {
	return file_agent_pb_metrics_proto_rawDescGZIP(), []int{9}
}

func (x *ApplicationMetrics) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ApplicationMetrics) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ApplicationMetrics) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ApplicationMetrics) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// GetApplicationMetricsReq 获取应用指标请求
type GetApplicationMetricsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 可选：服务名称，为空则返回所有服务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationMetricsReq) Reset() {
	*x = GetApplicationMetricsReq{}
	mi := &file_agent_pb_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationMetricsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationMetricsReq) ProtoMessage() {}

func (x *GetApplicationMetricsReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationMetricsReq.ProtoReflect.Descriptor instead.
func (*GetApplicationMetricsReq) Descriptor() ([]byte, []int) {
	return file_agent_pb_metrics_proto_rawDescGZIP(), []int{10}
}

func (x *GetApplicationMetricsReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// GetApplicationMetricsResp 获取应用指标响应
type GetApplicationMetricsResp struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Services      map[string]*ApplicationMetrics `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 服务名称 -> 应用指标
	Metrics       *ApplicationMetrics            `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`                                                                             // 单个服务的指标（当指定 service_name 时）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationMetricsResp) Reset() {
	*x = GetApplicationMetricsResp{}
	mi := &file_agent_pb_metrics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationMetricsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationMetricsResp) ProtoMessage() {}

func (x *GetApplicationMetricsResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_metrics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationMetricsResp.ProtoReflect.Descriptor instead.
func (*GetApplicationMetricsResp) Descriptor() ([]byte, []int) {
	return file_agent_pb_metrics_proto_rawDescGZIP(), []int{11}
}

func (x *GetApplicationMetricsResp) GetServices() map[string]*ApplicationMetrics {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *GetApplicationMetricsResp) GetMetrics() *ApplicationMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// GetMetricsHistoryReq 获取指标历史请求
type GetMetricsHistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                  // 指标类型：system, service
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 服务名称（仅当 type=service 时）
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`       // 开始时间
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`             // 结束时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsHistoryReq) Reset() {
	*x = GetMetricsHistoryReq{}
	mi := &file_agent_pb_metrics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsHistoryReq) ProtoMessage() {}

func (x *GetMetricsHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_metrics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsHistoryReq.ProtoReflect.Descriptor instead.
func (*GetMetricsHistoryReq) Descriptor() ([]byte, []int) {
	return file_agent_pb_metrics_proto_rawDescGZIP(), []int{12}
}

func (x *GetMetricsHistoryReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetMetricsHistoryReq) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetMetricsHistoryReq) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetMetricsHistoryReq) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// MetricsHistoryPoint 指标历史数据点
type MetricsHistoryPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       map[string]string      `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 指标数据（JSON 字符串格式）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsHistoryPoint) Reset() {
	*x = MetricsHistoryPoint{}
	mi := &file_agent_pb_metrics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsHistoryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsHistoryPoint) ProtoMessage() {}

func (x *MetricsHistoryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_metrics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsHistoryPoint.ProtoReflect.Descriptor instead.
func (*MetricsHistoryPoint) Descriptor() ([]byte, []int) {
	return file_agent_pb_metrics_proto_rawDescGZIP(), []int{13}
}

func (x *MetricsHistoryPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricsHistoryPoint) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// GetMetricsHistoryResp 获取指标历史响应
type GetMetricsHistoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DataPoints    []*MetricsHistoryPoint `protobuf:"bytes,5,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsHistoryResp) Reset() {
	*x = GetMetricsHistoryResp{}
	mi := &file_agent_pb_metrics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsHistoryResp) ProtoMessage() {}

func (x *GetMetricsHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_pb_metrics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsHistoryResp.ProtoReflect.Descriptor instead.
func (*GetMetricsHistoryResp) Descriptor() ([]byte, []int) {
	return file_agent_pb_metrics_proto_rawDescGZIP(), []int{14}
}

func (x *GetMetricsHistoryResp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetMetricsHistoryResp) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetMetricsHistoryResp) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetMetricsHistoryResp) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetMetricsHistoryResp) GetDataPoints() []*MetricsHistoryPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

var File_agent_pb_metrics_proto protoreflect.FileDescriptor

const file_agent_pb_metrics_proto_rawDesc = "" +
	"\n" +
	"\x16agent/pb/metrics.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x03\n" +
	"\x0eServiceMetrics\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x01R\vmemoryUsage\x12!\n" +
	"\fmemory_bytes\x18\x04 \x01(\x03R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x05 \x01(\x01R\tdiskUsage\x12\x1d\n" +
	"\n" +
	"network_in\x18\x06 \x01(\x03R\tnetworkIn\x12\x1f\n" +
	"\vnetwork_out\x18\a \x01(\x03R\n" +
	"networkOut\x12#\n" +
	"\rrequest_count\x18\b \x01(\x03R\frequestCount\x12\x1f\n" +
	"\verror_count\x18\t \x01(\x03R\n" +
	"errorCount\x12(\n" +
	"\x10response_time_ms\x18\n" +
	" \x01(\x03R\x0eresponseTimeMs\x12=\n" +
	"\flast_updated\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\\\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x03R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x03R\atxBytes\"\xab\x04\n" +
	"\rSystemMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12\x1b\n" +
	"\tcpu_cores\x18\x0e \x01(\x05R\bcpuCores\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12!\n" +
	"\fmemory_total\x18\x03 \x01(\x03R\vmemoryTotal\x12\x1f\n" +
	"\vmemory_free\x18\x04 \x01(\x03R\n" +
	"memoryFree\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x05 \x01(\x01R\tdiskUsage\x12\x1d\n" +
	"\n" +
	"disk_total\x18\x06 \x01(\x03R\tdiskTotal\x12\x1b\n" +
	"\tdisk_free\x18\a \x01(\x03R\bdiskFree\x12\x1d\n" +
	"\n" +
	"network_in\x18\b \x01(\x03R\tnetworkIn\x12\x1f\n" +
	"\vnetwork_out\x18\t \x01(\x03R\n" +
	"networkOut\x12C\n" +
	"\x12network_interfaces\x18\x0f \x03(\v2\x14.pb.NetworkInterfaceR\x11networkInterfaces\x12\x1c\n" +
	"\n" +
	"load_avg_1\x18\n" +
	" \x01(\x01R\bloadAvg1\x12\x1c\n" +
	"\n" +
	"load_avg_5\x18\v \x01(\x01R\bloadAvg5\x12\x1e\n" +
	"\vload_avg_15\x18\f \x01(\x01R\tloadAvg15\x12=\n" +
	"\flast_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\x15\n" +
	"\x13GetSystemMetricsReq\"C\n" +
	"\x14GetSystemMetricsResp\x12+\n" +
	"\ametrics\x18\x01 \x01(\v2\x11.pb.SystemMetricsR\ametrics\"0\n" +
	"\x14GetServiceMetricsReq\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\"E\n" +
	"\x15GetServiceMetricsResp\x12,\n" +
	"\ametrics\x18\x01 \x01(\v2\x12.pb.ServiceMetricsR\ametrics\":\n" +
	"\x15ListServiceMetricsReq\x12!\n" +
	"\frunning_only\x18\x01 \x01(\bR\vrunningOnly\"F\n" +
	"\x16ListServiceMetricsResp\x12,\n" +
	"\ametrics\x18\x01 \x03(\v2\x12.pb.ServiceMetricsR\ametrics\"\xe3\x02\n" +
	"\x12ApplicationMetrics\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12=\n" +
	"\ametrics\x18\x02 \x03(\v2#.pb.ApplicationMetrics.MetricsEntryR\ametrics\x12:\n" +
	"\x06labels\x18\x03 \x03(\v2\".pb.ApplicationMetrics.LabelsEntryR\x06labels\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x18GetApplicationMetricsReq\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\xeb\x01\n" +
	"\x19GetApplicationMetricsResp\x12G\n" +
	"\bservices\x18\x01 \x03(\v2+.pb.GetApplicationMetricsResp.ServicesEntryR\bservices\x120\n" +
	"\ametrics\x18\x02 \x01(\v2\x16.pb.ApplicationMetricsR\ametrics\x1aS\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.pb.ApplicationMetricsR\x05value:\x028\x01\"\xbf\x01\n" +
	"\x14GetMetricsHistoryReq\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xcb\x01\n" +
	"\x13MetricsHistoryPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12>\n" +
	"\ametrics\x18\x02 \x03(\v2$.pb.MetricsHistoryPoint.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x01\n" +
	"\x15GetMetricsHistoryResp\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x128\n" +
	"\vdata_points\x18\x05 \x03(\v2\x17.pb.MetricsHistoryPointR\n" +
	"dataPoints2\x87\x03\n" +
	"\aMetrics\x12E\n" +
	"\x10GetSystemMetrics\x12\x17.pb.GetSystemMetricsReq\x1a\x18.pb.GetSystemMetricsResp\x12H\n" +
	"\x11GetServiceMetrics\x12\x18.pb.GetServiceMetricsReq\x1a\x19.pb.GetServiceMetricsResp\x12K\n" +
	"\x12ListServiceMetrics\x12\x19.pb.ListServiceMetricsReq\x1a\x1a.pb.ListServiceMetricsResp\x12T\n" +
	"\x15GetApplicationMetrics\x12\x1c.pb.GetApplicationMetricsReq\x1a\x1d.pb.GetApplicationMetricsResp\x12H\n" +
	"\x11GetMetricsHistory\x12\x18.pb.GetMetricsHistoryReq\x1a\x19.pb.GetMetricsHistoryRespB\x1dZ\x1bgithub.com/influxdata/telegraf/controller/pbb\x06proto3"

var (
	file_agent_pb_metrics_proto_rawDescOnce sync.Once
	file_agent_pb_metrics_proto_rawDescData []byte
)

func file_agent_pb_metrics_proto_rawDescGZIP() []byte {
	file_agent_pb_metrics_proto_rawDescOnce.Do(func() {
		file_agent_pb_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_pb_metrics_proto_rawDesc), len(file_agent_pb_metrics_proto_rawDesc)))
	})
	return file_agent_pb_metrics_proto_rawDescData
}

var file_agent_pb_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_agent_pb_metrics_proto_goTypes = []any{
	(*ServiceMetrics)(nil),            // 0: pb.ServiceMetrics
	(*NetworkInterface)(nil),          // 1: pb.NetworkInterface
	(*SystemMetrics)(nil),             // 2: pb.SystemMetrics
	(*GetSystemMetricsReq)(nil),       // 3: pb.GetSystemMetricsReq
	(*GetSystemMetricsResp)(nil),      // 4: pb.GetSystemMetricsResp
	(*GetServiceMetricsReq)(nil),      // 5: pb.GetServiceMetricsReq
	(*GetServiceMetricsResp)(nil),     // 6: pb.GetServiceMetricsResp
	(*ListServiceMetricsReq)(nil),     // 7: pb.ListServiceMetricsReq
	(*ListServiceMetricsResp)(nil),    // 8: pb.ListServiceMetricsResp
	(*ApplicationMetrics)(nil),        // 9: pb.ApplicationMetrics
	(*GetApplicationMetricsReq)(nil),  // 10: pb.GetApplicationMetricsReq
	(*GetApplicationMetricsResp)(nil), // 11: pb.GetApplicationMetricsResp
	(*GetMetricsHistoryReq)(nil),      // 12: pb.GetMetricsHistoryReq
	(*MetricsHistoryPoint)(nil),       // 13: pb.MetricsHistoryPoint
	(*GetMetricsHistoryResp)(nil),     // 14: pb.GetMetricsHistoryResp
	nil,                               // 15: pb.ApplicationMetrics.MetricsEntry
	nil,                               // 16: pb.ApplicationMetrics.LabelsEntry
	nil,                               // 17: pb.GetApplicationMetricsResp.ServicesEntry
	nil,                               // 18: pb.MetricsHistoryPoint.MetricsEntry
	(*timestamppb.Timestamp)(nil),     // 19: google.protobuf.Timestamp
}
var file_agent_pb_metrics_proto_depIdxs = []int32{
	19, // 0: pb.ServiceMetrics.last_updated:type_name -> google.protobuf.Timestamp
	1,  // 1: pb.SystemMetrics.network_interfaces:type_name -> pb.NetworkInterface
	19, // 2: pb.SystemMetrics.last_updated:type_name -> google.protobuf.Timestamp
	2,  // 3: pb.GetSystemMetricsResp.metrics:type_name -> pb.SystemMetrics
	0,  // 4: pb.GetServiceMetricsResp.metrics:type_name -> pb.ServiceMetrics
	0,  // 5: pb.ListServiceMetricsResp.metrics:type_name -> pb.ServiceMetrics
	15, // 6: pb.ApplicationMetrics.metrics:type_name -> pb.ApplicationMetrics.MetricsEntry
	16, // 7: pb.ApplicationMetrics.labels:type_name -> pb.ApplicationMetrics.LabelsEntry
	19, // 8: pb.ApplicationMetrics.timestamp:type_name -> google.protobuf.Timestamp
	17, // 9: pb.GetApplicationMetricsResp.services:type_name -> pb.GetApplicationMetricsResp.ServicesEntry
	9,  // 10: pb.GetApplicationMetricsResp.metrics:type_name -> pb.ApplicationMetrics
	19, // 11: pb.GetMetricsHistoryReq.start_time:type_name -> google.protobuf.Timestamp
	19, // 12: pb.GetMetricsHistoryReq.end_time:type_name -> google.protobuf.Timestamp
	19, // 13: pb.MetricsHistoryPoint.timestamp:type_name -> google.protobuf.Timestamp
	18, // 14: pb.MetricsHistoryPoint.metrics:type_name -> pb.MetricsHistoryPoint.MetricsEntry
	19, // 15: pb.GetMetricsHistoryResp.start_time:type_name -> google.protobuf.Timestamp
	19, // 16: pb.GetMetricsHistoryResp.end_time:type_name -> google.protobuf.Timestamp
	13, // 17: pb.GetMetricsHistoryResp.data_points:type_name -> pb.MetricsHistoryPoint
	9,  // 18: pb.GetApplicationMetricsResp.ServicesEntry.value:type_name -> pb.ApplicationMetrics
	3,  // 19: pb.Metrics.GetSystemMetrics:input_type -> pb.GetSystemMetricsReq
	5,  // 20: pb.Metrics.GetServiceMetrics:input_type -> pb.GetServiceMetricsReq
	7,  // 21: pb.Metrics.ListServiceMetrics:input_type -> pb.ListServiceMetricsReq
	10, // 22: pb.Metrics.GetApplicationMetrics:input_type -> pb.GetApplicationMetricsReq
	12, // 23: pb.Metrics.GetMetricsHistory:input_type -> pb.GetMetricsHistoryReq
	4,  // 24: pb.Metrics.GetSystemMetrics:output_type -> pb.GetSystemMetricsResp
	6,  // 25: pb.Metrics.GetServiceMetrics:output_type -> pb.GetServiceMetricsResp
	8,  // 26: pb.Metrics.ListServiceMetrics:output_type -> pb.ListServiceMetricsResp
	11, // 27: pb.Metrics.GetApplicationMetrics:output_type -> pb.GetApplicationMetricsResp
	14, // 28: pb.Metrics.GetMetricsHistory:output_type -> pb.GetMetricsHistoryResp
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_agent_pb_metrics_proto_init() }
func file_agent_pb_metrics_proto_init() {
	if File_agent_pb_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_pb_metrics_proto_rawDesc), len(file_agent_pb_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_pb_metrics_proto_goTypes,
		DependencyIndexes: file_agent_pb_metrics_proto_depIdxs,
		MessageInfos:      file_agent_pb_metrics_proto_msgTypes,
	}.Build()
	File_agent_pb_metrics_proto = out.File
	file_agent_pb_metrics_proto_goTypes = nil
	file_agent_pb_metrics_proto_depIdxs = nil
}
