// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: agent/pb/metrics.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Metrics_GetSystemMetrics_FullMethodName      = "/pb.Metrics/GetSystemMetrics"
	Metrics_GetServiceMetrics_FullMethodName     = "/pb.Metrics/GetServiceMetrics"
	Metrics_ListServiceMetrics_FullMethodName    = "/pb.Metrics/ListServiceMetrics"
	Metrics_GetApplicationMetrics_FullMethodName = "/pb.Metrics/GetApplicationMetrics"
	Metrics_GetMetricsHistory_FullMethodName     = "/pb.Metrics/GetMetricsHistory"
)

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Metrics 服务定义
type MetricsClient interface {
	// GetSystemMetrics 获取系统指标
	GetSystemMetrics(ctx context.Context, in *GetSystemMetricsReq, opts ...grpc.CallOption) (*GetSystemMetricsResp, error)
	// GetServiceMetrics 获取指定服务的指标
	GetServiceMetrics(ctx context.Context, in *GetServiceMetricsReq, opts ...grpc.CallOption) (*GetServiceMetricsResp, error)
	// ListServiceMetrics 列出所有服务的指标
	ListServiceMetrics(ctx context.Context, in *ListServiceMetricsReq, opts ...grpc.CallOption) (*ListServiceMetricsResp, error)
	// GetApplicationMetrics 获取应用指标
	GetApplicationMetrics(ctx context.Context, in *GetApplicationMetricsReq, opts ...grpc.CallOption) (*GetApplicationMetricsResp, error)
	// GetMetricsHistory 获取指标历史数据
	GetMetricsHistory(ctx context.Context, in *GetMetricsHistoryReq, opts ...grpc.CallOption) (*GetMetricsHistoryResp, error)
}

type metricsClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsClient(cc grpc.ClientConnInterface) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) GetSystemMetrics(ctx context.Context, in *GetSystemMetricsReq, opts ...grpc.CallOption) (*GetSystemMetricsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSystemMetricsResp)
	err := c.cc.Invoke(ctx, Metrics_GetSystemMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) GetServiceMetrics(ctx context.Context, in *GetServiceMetricsReq, opts ...grpc.CallOption) (*GetServiceMetricsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceMetricsResp)
	err := c.cc.Invoke(ctx, Metrics_GetServiceMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) ListServiceMetrics(ctx context.Context, in *ListServiceMetricsReq, opts ...grpc.CallOption) (*ListServiceMetricsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServiceMetricsResp)
	err := c.cc.Invoke(ctx, Metrics_ListServiceMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) GetApplicationMetrics(ctx context.Context, in *GetApplicationMetricsReq, opts ...grpc.CallOption) (*GetApplicationMetricsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApplicationMetricsResp)
	err := c.cc.Invoke(ctx, Metrics_GetApplicationMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) GetMetricsHistory(ctx context.Context, in *GetMetricsHistoryReq, opts ...grpc.CallOption) (*GetMetricsHistoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsHistoryResp)
	err := c.cc.Invoke(ctx, Metrics_GetMetricsHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServer is the server API for Metrics service.
// All implementations must embed UnimplementedMetricsServer
// for forward compatibility.
//
// Metrics 服务定义
type MetricsServer interface {
	// GetSystemMetrics 获取系统指标
	GetSystemMetrics(context.Context, *GetSystemMetricsReq) (*GetSystemMetricsResp, error)
	// GetServiceMetrics 获取指定服务的指标
	GetServiceMetrics(context.Context, *GetServiceMetricsReq) (*GetServiceMetricsResp, error)
	// ListServiceMetrics 列出所有服务的指标
	ListServiceMetrics(context.Context, *ListServiceMetricsReq) (*ListServiceMetricsResp, error)
	// GetApplicationMetrics 获取应用指标
	GetApplicationMetrics(context.Context, *GetApplicationMetricsReq) (*GetApplicationMetricsResp, error)
	// GetMetricsHistory 获取指标历史数据
	GetMetricsHistory(context.Context, *GetMetricsHistoryReq) (*GetMetricsHistoryResp, error)
	mustEmbedUnimplementedMetricsServer()
}

// UnimplementedMetricsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsServer struct{}

func (UnimplementedMetricsServer) GetSystemMetrics(context.Context, *GetSystemMetricsReq) (*GetSystemMetricsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemMetrics not implemented")
}
func (UnimplementedMetricsServer) GetServiceMetrics(context.Context, *GetServiceMetricsReq) (*GetServiceMetricsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceMetrics not implemented")
}
func (UnimplementedMetricsServer) ListServiceMetrics(context.Context, *ListServiceMetricsReq) (*ListServiceMetricsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServiceMetrics not implemented")
}
func (UnimplementedMetricsServer) GetApplicationMetrics(context.Context, *GetApplicationMetricsReq) (*GetApplicationMetricsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplicationMetrics not implemented")
}
func (UnimplementedMetricsServer) GetMetricsHistory(context.Context, *GetMetricsHistoryReq) (*GetMetricsHistoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetricsHistory not implemented")
}
func (UnimplementedMetricsServer) mustEmbedUnimplementedMetricsServer() {}
func (UnimplementedMetricsServer) testEmbeddedByValue()                 {}

// UnsafeMetricsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServer will
// result in compilation errors.
type UnsafeMetricsServer interface {
	mustEmbedUnimplementedMetricsServer()
}

func RegisterMetricsServer(s grpc.ServiceRegistrar, srv MetricsServer) {
	// If the following call panics, it indicates UnimplementedMetricsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Metrics_ServiceDesc, srv)
}

func _Metrics_GetSystemMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemMetricsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).GetSystemMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_GetSystemMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).GetSystemMetrics(ctx, req.(*GetSystemMetricsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_GetServiceMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceMetricsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).GetServiceMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_GetServiceMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).GetServiceMetrics(ctx, req.(*GetServiceMetricsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_ListServiceMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServiceMetricsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).ListServiceMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_ListServiceMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).ListServiceMetrics(ctx, req.(*ListServiceMetricsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_GetApplicationMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationMetricsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).GetApplicationMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_GetApplicationMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).GetApplicationMetrics(ctx, req.(*GetApplicationMetricsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_GetMetricsHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).GetMetricsHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_GetMetricsHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).GetMetricsHistory(ctx, req.(*GetMetricsHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Metrics_ServiceDesc is the grpc.ServiceDesc for Metrics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metrics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemMetrics",
			Handler:    _Metrics_GetSystemMetrics_Handler,
		},
		{
			MethodName: "GetServiceMetrics",
			Handler:    _Metrics_GetServiceMetrics_Handler,
		},
		{
			MethodName: "ListServiceMetrics",
			Handler:    _Metrics_ListServiceMetrics_Handler,
		},
		{
			MethodName: "GetApplicationMetrics",
			Handler:    _Metrics_GetApplicationMetrics_Handler,
		},
		{
			MethodName: "GetMetricsHistory",
			Handler:    _Metrics_GetMetricsHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/pb/metrics.proto",
}
