// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: package.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutputFormat int32

const (
	OutputFormat_JSON OutputFormat = 0
	OutputFormat_YAML OutputFormat = 1
	OutputFormat_TOML OutputFormat = 2
)

// Enum value maps for OutputFormat.
var (
	OutputFormat_name = map[int32]string{
		0: "JSON",
		1: "YAML",
		2: "TOML",
	}
	OutputFormat_value = map[string]int32{
		"JSON": 0,
		"YAML": 1,
		"TOML": 2,
	}
)

func (x OutputFormat) Enum() *OutputFormat {
	p := new(OutputFormat)
	*p = x
	return p
}

func (x OutputFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_package_proto_enumTypes[0].Descriptor()
}

func (OutputFormat) Type() protoreflect.EnumType {
	return &file_package_proto_enumTypes[0]
}

func (x OutputFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputFormat.Descriptor instead.
func (OutputFormat) EnumDescriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{0}
}

type StartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartReq) Reset() {
	*x = StartReq{}
	mi := &file_package_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReq) ProtoMessage() {}

func (x *StartReq) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReq.ProtoReflect.Descriptor instead.
func (*StartReq) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{0}
}

func (x *StartReq) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

type StopReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopReq) Reset() {
	*x = StopReq{}
	mi := &file_package_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopReq) ProtoMessage() {}

func (x *StopReq) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopReq.ProtoReflect.Descriptor instead.
func (*StopReq) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{1}
}

func (x *StopReq) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

type RestartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartReq) Reset() {
	*x = RestartReq{}
	mi := &file_package_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartReq) ProtoMessage() {}

func (x *RestartReq) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartReq.ProtoReflect.Descriptor instead.
func (*RestartReq) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{2}
}

func (x *RestartReq) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

type PackItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Package         string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	IsRunning       bool                   `protobuf:"varint,2,opt,name=isRunning,proto3" json:"isRunning,omitempty"`
	Schema          string                 `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	Version         string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	RunningDuration int64                  `protobuf:"varint,5,opt,name=running_duration,json=runningDuration,proto3" json:"running_duration,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PackItem) Reset() {
	*x = PackItem{}
	mi := &file_package_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackItem) ProtoMessage() {}

func (x *PackItem) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackItem.ProtoReflect.Descriptor instead.
func (*PackItem) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{3}
}

func (x *PackItem) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *PackItem) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

func (x *PackItem) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *PackItem) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackItem) GetRunningDuration() int64 {
	if x != nil {
		return x.RunningDuration
	}
	return 0
}

type PackageListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentCode     string                 `protobuf:"bytes,1,opt,name=agentCode,proto3" json:"agentCode,omitempty"`
	Packages      []*PackItem            `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageListResp) Reset() {
	*x = PackageListResp{}
	mi := &file_package_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageListResp) ProtoMessage() {}

func (x *PackageListResp) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageListResp.ProtoReflect.Descriptor instead.
func (*PackageListResp) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{4}
}

func (x *PackageListResp) GetAgentCode() string {
	if x != nil {
		return x.AgentCode
	}
	return ""
}

func (x *PackageListResp) GetPackages() []*PackItem {
	if x != nil {
		return x.Packages
	}
	return nil
}

type ListConfigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`                     // 服务包名称
	ConfName      string                 `protobuf:"bytes,2,opt,name=confName,proto3" json:"confName,omitempty"`                   // 配置文件名称
	Format        OutputFormat           `protobuf:"varint,3,opt,name=format,proto3,enum=pb.OutputFormat" json:"format,omitempty"` // 输出格式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigReq) Reset() {
	*x = ListConfigReq{}
	mi := &file_package_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigReq) ProtoMessage() {}

func (x *ListConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigReq.ProtoReflect.Descriptor instead.
func (*ListConfigReq) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{5}
}

func (x *ListConfigReq) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *ListConfigReq) GetConfName() string {
	if x != nil {
		return x.ConfName
	}
	return ""
}

func (x *ListConfigReq) GetFormat() OutputFormat {
	if x != nil {
		return x.Format
	}
	return OutputFormat_JSON
}

// GetConfigReq 用于请求获取配置
type GetConfigsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"` // 包名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigsReq) Reset() {
	*x = GetConfigsReq{}
	mi := &file_package_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigsReq) ProtoMessage() {}

func (x *GetConfigsReq) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigsReq.ProtoReflect.Descriptor instead.
func (*GetConfigsReq) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{6}
}

func (x *GetConfigsReq) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

// GetConfigResp 用于返回配置信息
type GetConfigsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*ConfigItem          `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigsResp) Reset() {
	*x = GetConfigsResp{}
	mi := &file_package_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigsResp) ProtoMessage() {}

func (x *GetConfigsResp) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigsResp.ProtoReflect.Descriptor instead.
func (*GetConfigsResp) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{7}
}

func (x *GetConfigsResp) GetConfigs() []*ConfigItem {
	if x != nil {
		return x.Configs
	}
	return nil
}

// ConfigItem 表示一个配置项
type ConfigItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // 配置键
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                   // 配置内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItem) Reset() {
	*x = ConfigItem{}
	mi := &file_package_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItem) ProtoMessage() {}

func (x *ConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItem.ProtoReflect.Descriptor instead.
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigItem) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ConfigItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ApplyConfigsReq 用于请求应用配置
type ApplyConfigsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"` // 包名
	Configs       []*ConfigItem          `protobuf:"bytes,2,rep,name=configs,proto3" json:"configs,omitempty"` // 要应用的配置项列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyConfigsReq) Reset() {
	*x = ApplyConfigsReq{}
	mi := &file_package_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfigsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfigsReq) ProtoMessage() {}

func (x *ApplyConfigsReq) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfigsReq.ProtoReflect.Descriptor instead.
func (*ApplyConfigsReq) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{9}
}

func (x *ApplyConfigsReq) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *ApplyConfigsReq) GetConfigs() []*ConfigItem {
	if x != nil {
		return x.Configs
	}
	return nil
}

type UpdatedFileDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ByteCount     int32                  `protobuf:"varint,2,opt,name=byte_count,json=byteCount,proto3" json:"byte_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatedFileDetail) Reset() {
	*x = UpdatedFileDetail{}
	mi := &file_package_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatedFileDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedFileDetail) ProtoMessage() {}

func (x *UpdatedFileDetail) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedFileDetail.ProtoReflect.Descriptor instead.
func (*UpdatedFileDetail) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatedFileDetail) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UpdatedFileDetail) GetByteCount() int32 {
	if x != nil {
		return x.ByteCount
	}
	return 0
}

// ApplyConfigsResp 用于应用配置的响应
type ApplyConfigsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedFiles  []*UpdatedFileDetail   `protobuf:"bytes,3,rep,name=updated_files,json=updatedFiles,proto3" json:"updated_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyConfigsResp) Reset() {
	*x = ApplyConfigsResp{}
	mi := &file_package_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfigsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfigsResp) ProtoMessage() {}

func (x *ApplyConfigsResp) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfigsResp.ProtoReflect.Descriptor instead.
func (*ApplyConfigsResp) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{11}
}

func (x *ApplyConfigsResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyConfigsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApplyConfigsResp) GetUpdatedFiles() []*UpdatedFileDetail {
	if x != nil {
		return x.UpdatedFiles
	}
	return nil
}

type GetRecentLogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentLogsReq) Reset() {
	*x = GetRecentLogsReq{}
	mi := &file_package_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentLogsReq) ProtoMessage() {}

func (x *GetRecentLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentLogsReq.ProtoReflect.Descriptor instead.
func (*GetRecentLogsReq) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{12}
}

func (x *GetRecentLogsReq) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *GetRecentLogsReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetRecentLogsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []string               `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentLogsResp) Reset() {
	*x = GetRecentLogsResp{}
	mi := &file_package_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentLogsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentLogsResp) ProtoMessage() {}

func (x *GetRecentLogsResp) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentLogsResp.ProtoReflect.Descriptor instead.
func (*GetRecentLogsResp) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{13}
}

func (x *GetRecentLogsResp) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

type StreamLogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	TailLines     int32                  `protobuf:"varint,2,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"` // 初始返回的行数，0 表示不返回历史日志
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`                        // 是否持续跟踪新日志
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsReq) Reset() {
	*x = StreamLogsReq{}
	mi := &file_package_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsReq) ProtoMessage() {}

func (x *StreamLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsReq.ProtoReflect.Descriptor instead.
func (*StreamLogsReq) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{14}
}

func (x *StreamLogsReq) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *StreamLogsReq) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *StreamLogsReq) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type StreamLogsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogLine       string                 `protobuf:"bytes,1,opt,name=log_line,json=logLine,proto3" json:"log_line,omitempty"`
	IsEof         bool                   `protobuf:"varint,2,opt,name=is_eof,json=isEof,proto3" json:"is_eof,omitempty"` // 是否到达文件末尾（仅在 follow=false 时使用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsResp) Reset() {
	*x = StreamLogsResp{}
	mi := &file_package_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsResp) ProtoMessage() {}

func (x *StreamLogsResp) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsResp.ProtoReflect.Descriptor instead.
func (*StreamLogsResp) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{15}
}

func (x *StreamLogsResp) GetLogLine() string {
	if x != nil {
		return x.LogLine
	}
	return ""
}

func (x *StreamLogsResp) GetIsEof() bool {
	if x != nil {
		return x.IsEof
	}
	return false
}

type QueryLogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`                       // 搜索关键词（可选）
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`                           // 日志级别过滤（可选，如 "error", "warn", "info"）
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 开始时间戳（Unix 时间戳，秒）
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 结束时间戳（Unix 时间戳，秒）
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`                          // 返回的最大行数
	Offset        int32                  `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`                        // 偏移量（用于分页）
	Reverse       bool                   `protobuf:"varint,8,opt,name=reverse,proto3" json:"reverse,omitempty"`                      // 是否反向排序（true 表示从新到旧）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLogsReq) Reset() {
	*x = QueryLogsReq{}
	mi := &file_package_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogsReq) ProtoMessage() {}

func (x *QueryLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogsReq.ProtoReflect.Descriptor instead.
func (*QueryLogsReq) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{16}
}

func (x *QueryLogsReq) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *QueryLogsReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *QueryLogsReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *QueryLogsReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *QueryLogsReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *QueryLogsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryLogsReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryLogsReq) GetReverse() bool {
	if x != nil {
		return x.Reverse
	}
	return false
}

type QueryLogsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []string               `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                    // 总行数（匹配条件的）
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"` // 是否还有更多结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLogsResp) Reset() {
	*x = QueryLogsResp{}
	mi := &file_package_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogsResp) ProtoMessage() {}

func (x *QueryLogsResp) ProtoReflect() protoreflect.Message {
	mi := &file_package_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogsResp.ProtoReflect.Descriptor instead.
func (*QueryLogsResp) Descriptor() ([]byte, []int) {
	return file_package_proto_rawDescGZIP(), []int{17}
}

func (x *QueryLogsResp) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *QueryLogsResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryLogsResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_package_proto protoreflect.FileDescriptor

const file_package_proto_rawDesc = "" +
	"\n" +
	"\rpackage.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\"$\n" +
	"\bStartReq\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\"#\n" +
	"\aStopReq\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\"&\n" +
	"\n" +
	"RestartReq\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\"\x9f\x01\n" +
	"\bPackItem\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x1c\n" +
	"\tisRunning\x18\x02 \x01(\bR\tisRunning\x12\x16\n" +
	"\x06schema\x18\x03 \x01(\tR\x06schema\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12)\n" +
	"\x10running_duration\x18\x05 \x01(\x03R\x0frunningDuration\"Y\n" +
	"\x0fPackageListResp\x12\x1c\n" +
	"\tagentCode\x18\x01 \x01(\tR\tagentCode\x12(\n" +
	"\bpackages\x18\x02 \x03(\v2\f.pb.PackItemR\bpackages\"o\n" +
	"\rListConfigReq\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x1a\n" +
	"\bconfName\x18\x02 \x01(\tR\bconfName\x12(\n" +
	"\x06format\x18\x03 \x01(\x0e2\x10.pb.OutputFormatR\x06format\")\n" +
	"\rGetConfigsReq\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\":\n" +
	"\x0eGetConfigsResp\x12(\n" +
	"\aconfigs\x18\x01 \x03(\v2\x0e.pb.ConfigItemR\aconfigs\"C\n" +
	"\n" +
	"ConfigItem\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"U\n" +
	"\x0fApplyConfigsReq\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12(\n" +
	"\aconfigs\x18\x02 \x03(\v2\x0e.pb.ConfigItemR\aconfigs\"O\n" +
	"\x11UpdatedFileDetail\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"byte_count\x18\x02 \x01(\x05R\tbyteCount\"\x82\x01\n" +
	"\x10ApplyConfigsResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\rupdated_files\x18\x03 \x03(\v2\x15.pb.UpdatedFileDetailR\fupdatedFiles\"B\n" +
	"\x10GetRecentLogsReq\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"'\n" +
	"\x11GetRecentLogsResp\x12\x12\n" +
	"\x04logs\x18\x01 \x03(\tR\x04logs\"`\n" +
	"\rStreamLogsReq\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x02 \x01(\x05R\ttailLines\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\"B\n" +
	"\x0eStreamLogsResp\x12\x19\n" +
	"\blog_line\x18\x01 \x01(\tR\alogLine\x12\x15\n" +
	"\x06is_eof\x18\x02 \x01(\bR\x05isEof\"\xda\x01\n" +
	"\fQueryLogsReq\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\a \x01(\x05R\x06offset\x12\x18\n" +
	"\areverse\x18\b \x01(\bR\areverse\"T\n" +
	"\rQueryLogsResp\x12\x12\n" +
	"\x04logs\x18\x01 \x03(\tR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore*,\n" +
	"\fOutputFormat\x12\b\n" +
	"\x04JSON\x10\x00\x12\b\n" +
	"\x04YAML\x10\x01\x12\b\n" +
	"\x04TOML\x10\x022\xf1\x03\n" +
	"\aPackage\x12-\n" +
	"\x05Start\x12\f.pb.StartReq\x1a\x16.google.protobuf.Empty\x12+\n" +
	"\x04Stop\x12\v.pb.StopReq\x1a\x16.google.protobuf.Empty\x121\n" +
	"\aRestart\x12\x0e.pb.RestartReq\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\vPackageList\x12\x16.google.protobuf.Empty\x1a\x13.pb.PackageListResp\x123\n" +
	"\n" +
	"GetConfigs\x12\x11.pb.GetConfigsReq\x1a\x12.pb.GetConfigsResp\x129\n" +
	"\fApplyConfigs\x12\x13.pb.ApplyConfigsReq\x1a\x14.pb.ApplyConfigsResp\x12>\n" +
	"\rGetRecentLogs\x12\x14.pb.GetRecentLogsReq\x1a\x15.pb.GetRecentLogsResp\"\x00\x127\n" +
	"\n" +
	"StreamLogs\x12\x11.pb.StreamLogsReq\x1a\x12.pb.StreamLogsResp\"\x000\x01\x122\n" +
	"\tQueryLogs\x12\x10.pb.QueryLogsReq\x1a\x11.pb.QueryLogsResp\"\x00B\x1dZ\x1bgithub.com/influxdata/telegraf/controller/pbb\x06proto3"

var (
	file_package_proto_rawDescOnce sync.Once
	file_package_proto_rawDescData []byte
)

func file_package_proto_rawDescGZIP() []byte {
	file_package_proto_rawDescOnce.Do(func() {
		file_package_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_package_proto_rawDesc), len(file_package_proto_rawDesc)))
	})
	return file_package_proto_rawDescData
}

var file_package_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_package_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_package_proto_goTypes = []any{
	(OutputFormat)(0),         // 0: pb.OutputFormat
	(*StartReq)(nil),          // 1: pb.StartReq
	(*StopReq)(nil),           // 2: pb.StopReq
	(*RestartReq)(nil),        // 3: pb.RestartReq
	(*PackItem)(nil),          // 4: pb.PackItem
	(*PackageListResp)(nil),   // 5: pb.PackageListResp
	(*ListConfigReq)(nil),     // 6: pb.ListConfigReq
	(*GetConfigsReq)(nil),     // 7: pb.GetConfigsReq
	(*GetConfigsResp)(nil),    // 8: pb.GetConfigsResp
	(*ConfigItem)(nil),        // 9: pb.ConfigItem
	(*ApplyConfigsReq)(nil),   // 10: pb.ApplyConfigsReq
	(*UpdatedFileDetail)(nil), // 11: pb.UpdatedFileDetail
	(*ApplyConfigsResp)(nil),  // 12: pb.ApplyConfigsResp
	(*GetRecentLogsReq)(nil),  // 13: pb.GetRecentLogsReq
	(*GetRecentLogsResp)(nil), // 14: pb.GetRecentLogsResp
	(*StreamLogsReq)(nil),     // 15: pb.StreamLogsReq
	(*StreamLogsResp)(nil),    // 16: pb.StreamLogsResp
	(*QueryLogsReq)(nil),      // 17: pb.QueryLogsReq
	(*QueryLogsResp)(nil),     // 18: pb.QueryLogsResp
	(*emptypb.Empty)(nil),     // 19: google.protobuf.Empty
}
var file_package_proto_depIdxs = []int32{
	4,  // 0: pb.PackageListResp.packages:type_name -> pb.PackItem
	0,  // 1: pb.ListConfigReq.format:type_name -> pb.OutputFormat
	9,  // 2: pb.GetConfigsResp.configs:type_name -> pb.ConfigItem
	9,  // 3: pb.ApplyConfigsReq.configs:type_name -> pb.ConfigItem
	11, // 4: pb.ApplyConfigsResp.updated_files:type_name -> pb.UpdatedFileDetail
	1,  // 5: pb.Package.Start:input_type -> pb.StartReq
	2,  // 6: pb.Package.Stop:input_type -> pb.StopReq
	3,  // 7: pb.Package.Restart:input_type -> pb.RestartReq
	19, // 8: pb.Package.PackageList:input_type -> google.protobuf.Empty
	7,  // 9: pb.Package.GetConfigs:input_type -> pb.GetConfigsReq
	10, // 10: pb.Package.ApplyConfigs:input_type -> pb.ApplyConfigsReq
	13, // 11: pb.Package.GetRecentLogs:input_type -> pb.GetRecentLogsReq
	15, // 12: pb.Package.StreamLogs:input_type -> pb.StreamLogsReq
	17, // 13: pb.Package.QueryLogs:input_type -> pb.QueryLogsReq
	19, // 14: pb.Package.Start:output_type -> google.protobuf.Empty
	19, // 15: pb.Package.Stop:output_type -> google.protobuf.Empty
	19, // 16: pb.Package.Restart:output_type -> google.protobuf.Empty
	5,  // 17: pb.Package.PackageList:output_type -> pb.PackageListResp
	8,  // 18: pb.Package.GetConfigs:output_type -> pb.GetConfigsResp
	12, // 19: pb.Package.ApplyConfigs:output_type -> pb.ApplyConfigsResp
	14, // 20: pb.Package.GetRecentLogs:output_type -> pb.GetRecentLogsResp
	16, // 21: pb.Package.StreamLogs:output_type -> pb.StreamLogsResp
	18, // 22: pb.Package.QueryLogs:output_type -> pb.QueryLogsResp
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_package_proto_init() }
func file_package_proto_init() {
	if File_package_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_package_proto_rawDesc), len(file_package_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_package_proto_goTypes,
		DependencyIndexes: file_package_proto_depIdxs,
		EnumInfos:         file_package_proto_enumTypes,
		MessageInfos:      file_package_proto_msgTypes,
	}.Build()
	File_package_proto = out.File
	file_package_proto_goTypes = nil
	file_package_proto_depIdxs = nil
}
