// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: package.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Package_Start_FullMethodName         = "/pb.Package/Start"
	Package_Stop_FullMethodName          = "/pb.Package/Stop"
	Package_Restart_FullMethodName       = "/pb.Package/Restart"
	Package_PackageList_FullMethodName   = "/pb.Package/PackageList"
	Package_GetConfigs_FullMethodName    = "/pb.Package/GetConfigs"
	Package_ApplyConfigs_FullMethodName  = "/pb.Package/ApplyConfigs"
	Package_GetRecentLogs_FullMethodName = "/pb.Package/GetRecentLogs"
	Package_StreamLogs_FullMethodName    = "/pb.Package/StreamLogs"
	Package_QueryLogs_FullMethodName     = "/pb.Package/QueryLogs"
)

// PackageClient is the client API for Package service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 服务定义
type PackageClient interface {
	Start(ctx context.Context, in *StartReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Stop(ctx context.Context, in *StopReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Restart(ctx context.Context, in *RestartReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PackageList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PackageListResp, error)
	GetConfigs(ctx context.Context, in *GetConfigsReq, opts ...grpc.CallOption) (*GetConfigsResp, error)
	ApplyConfigs(ctx context.Context, in *ApplyConfigsReq, opts ...grpc.CallOption) (*ApplyConfigsResp, error)
	GetRecentLogs(ctx context.Context, in *GetRecentLogsReq, opts ...grpc.CallOption) (*GetRecentLogsResp, error)
	StreamLogs(ctx context.Context, in *StreamLogsReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamLogsResp], error)
	QueryLogs(ctx context.Context, in *QueryLogsReq, opts ...grpc.CallOption) (*QueryLogsResp, error)
}

type packageClient struct {
	cc grpc.ClientConnInterface
}

func NewPackageClient(cc grpc.ClientConnInterface) PackageClient {
	return &packageClient{cc}
}

func (c *packageClient) Start(ctx context.Context, in *StartReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Package_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageClient) Stop(ctx context.Context, in *StopReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Package_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageClient) Restart(ctx context.Context, in *RestartReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Package_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageClient) PackageList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PackageListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageListResp)
	err := c.cc.Invoke(ctx, Package_PackageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageClient) GetConfigs(ctx context.Context, in *GetConfigsReq, opts ...grpc.CallOption) (*GetConfigsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigsResp)
	err := c.cc.Invoke(ctx, Package_GetConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageClient) ApplyConfigs(ctx context.Context, in *ApplyConfigsReq, opts ...grpc.CallOption) (*ApplyConfigsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyConfigsResp)
	err := c.cc.Invoke(ctx, Package_ApplyConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageClient) GetRecentLogs(ctx context.Context, in *GetRecentLogsReq, opts ...grpc.CallOption) (*GetRecentLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecentLogsResp)
	err := c.cc.Invoke(ctx, Package_GetRecentLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *packageClient) StreamLogs(ctx context.Context, in *StreamLogsReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamLogsResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Package_ServiceDesc.Streams[0], Package_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsReq, StreamLogsResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Package_StreamLogsClient = grpc.ServerStreamingClient[StreamLogsResp]

func (c *packageClient) QueryLogs(ctx context.Context, in *QueryLogsReq, opts ...grpc.CallOption) (*QueryLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryLogsResp)
	err := c.cc.Invoke(ctx, Package_QueryLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PackageServer is the server API for Package service.
// All implementations must embed UnimplementedPackageServer
// for forward compatibility.
//
// 服务定义
type PackageServer interface {
	Start(context.Context, *StartReq) (*emptypb.Empty, error)
	Stop(context.Context, *StopReq) (*emptypb.Empty, error)
	Restart(context.Context, *RestartReq) (*emptypb.Empty, error)
	PackageList(context.Context, *emptypb.Empty) (*PackageListResp, error)
	GetConfigs(context.Context, *GetConfigsReq) (*GetConfigsResp, error)
	ApplyConfigs(context.Context, *ApplyConfigsReq) (*ApplyConfigsResp, error)
	GetRecentLogs(context.Context, *GetRecentLogsReq) (*GetRecentLogsResp, error)
	StreamLogs(*StreamLogsReq, grpc.ServerStreamingServer[StreamLogsResp]) error
	QueryLogs(context.Context, *QueryLogsReq) (*QueryLogsResp, error)
	mustEmbedUnimplementedPackageServer()
}

// UnimplementedPackageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPackageServer struct{}

func (UnimplementedPackageServer) Start(context.Context, *StartReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedPackageServer) Stop(context.Context, *StopReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedPackageServer) Restart(context.Context, *RestartReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedPackageServer) PackageList(context.Context, *emptypb.Empty) (*PackageListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PackageList not implemented")
}
func (UnimplementedPackageServer) GetConfigs(context.Context, *GetConfigsReq) (*GetConfigsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigs not implemented")
}
func (UnimplementedPackageServer) ApplyConfigs(context.Context, *ApplyConfigsReq) (*ApplyConfigsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyConfigs not implemented")
}
func (UnimplementedPackageServer) GetRecentLogs(context.Context, *GetRecentLogsReq) (*GetRecentLogsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecentLogs not implemented")
}
func (UnimplementedPackageServer) StreamLogs(*StreamLogsReq, grpc.ServerStreamingServer[StreamLogsResp]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedPackageServer) QueryLogs(context.Context, *QueryLogsReq) (*QueryLogsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLogs not implemented")
}
func (UnimplementedPackageServer) mustEmbedUnimplementedPackageServer() {}
func (UnimplementedPackageServer) testEmbeddedByValue()                 {}

// UnsafePackageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PackageServer will
// result in compilation errors.
type UnsafePackageServer interface {
	mustEmbedUnimplementedPackageServer()
}

func RegisterPackageServer(s grpc.ServiceRegistrar, srv PackageServer) {
	// If the following call pancis, it indicates UnimplementedPackageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Package_ServiceDesc, srv)
}

func _Package_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Package_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageServer).Start(ctx, req.(*StartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Package_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Package_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageServer).Stop(ctx, req.(*StopReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Package_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Package_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageServer).Restart(ctx, req.(*RestartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Package_PackageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageServer).PackageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Package_PackageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageServer).PackageList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Package_GetConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageServer).GetConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Package_GetConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageServer).GetConfigs(ctx, req.(*GetConfigsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Package_ApplyConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyConfigsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageServer).ApplyConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Package_ApplyConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageServer).ApplyConfigs(ctx, req.(*ApplyConfigsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Package_GetRecentLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageServer).GetRecentLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Package_GetRecentLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageServer).GetRecentLogs(ctx, req.(*GetRecentLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Package_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PackageServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsReq, StreamLogsResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Package_StreamLogsServer = grpc.ServerStreamingServer[StreamLogsResp]

func _Package_QueryLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PackageServer).QueryLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Package_QueryLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PackageServer).QueryLogs(ctx, req.(*QueryLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Package_ServiceDesc is the grpc.ServiceDesc for Package service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Package_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Package",
	HandlerType: (*PackageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Package_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Package_Stop_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _Package_Restart_Handler,
		},
		{
			MethodName: "PackageList",
			Handler:    _Package_PackageList_Handler,
		},
		{
			MethodName: "GetConfigs",
			Handler:    _Package_GetConfigs_Handler,
		},
		{
			MethodName: "ApplyConfigs",
			Handler:    _Package_ApplyConfigs_Handler,
		},
		{
			MethodName: "GetRecentLogs",
			Handler:    _Package_GetRecentLogs_Handler,
		},
		{
			MethodName: "QueryLogs",
			Handler:    _Package_QueryLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _Package_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "package.proto",
}
