//go:build ignore
// +build ignore

package main

import (
    "fmt"
    "io/ioutil"
    "os"
    "os/exec"
    "strings"
)

func main() {
    version := getVersion()
    content := fmt.Sprintf(`package version

// Code generated by go generate; DO NOT EDIT.

var Version = %q
`, version)

    err := ioutil.WriteFile("version_gen.go", []byte(content), 0644)
    if err != nil {
        fmt.Printf("Error writing version_gen.go: %v\n", err)
        os.Exit(1)
    }
}

func getVersion() string {
    // 尝试从 VERSION 文件读取
    if version, err := ioutil.ReadFile("../../VERSION"); err == nil {
        return strings.TrimSpace(string(version))
    }

    // 如果 VERSION 文件不存在，则从 git 标签获取
    cmd := exec.Command("git", "describe", "--tags", "--always", "--dirty")
    out, err := cmd.Output()
    if err != nil {
        fmt.Printf("Error getting version from git: %v\n", err)
        return "unknown"
    }
    return strings.TrimSpace(string(out))
}